from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def Union_930_reformat_0(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("`ED Visit Alw Amt`").cast(StringType()).alias("ED Visit Alw Amt"), 
        col("MBR_INDV_BE_KEY").cast(StringType()).alias("MBR_INDV_BE_KEY"), 
        col("`Household ED Visit Tot Alw Amt`").cast(StringType()).alias("Household ED Visit Tot Alw Amt"), 
        col("`Diag Codes`").alias("Diag Codes"), 
        col("`PCMH Attributed`").alias("PCMH Attributed"), 
        col("Target"), 
        col("`PCP Attributed`").alias("PCP Attributed"), 
        col("positive_probability").cast(StringType()).alias("positive_probability"), 
        col("`Max Claim Line Spend`").cast(StringType()).alias("Max Claim Line Spend"), 
        col("prediction_threshold").cast(StringType()).alias("prediction_threshold"), 
        col("`Total Claim Spend`").cast(StringType()).alias("Total Claim Spend"), 
        col("PR"), 
        col("ZIP"), 
        col("`Index Month`").alias("Index Month"), 
        col("`Drug/Alcohol/Psych Related ED Visit`").alias("Drug/Alcohol/Psych Related ED Visit"), 
        col("Last_YMD"), 
        col("`Group ID`").alias("Group ID"), 
        col("`Hospital Stay Days`").cast(StringType()).alias("Hospital Stay Days"), 
        col("`Service Area`").alias("Service Area"), 
        col("`CCI Score`").alias("CCI Score"), 
        col("`Non Emergent Percentage`").cast(StringType()).alias("Non Emergent Percentage"), 
        col("`Medical Home (str)`").alias("Medical Home (str)"), 
        col("`Coverage Area`").alias("Coverage Area"), 
        col("prediction").cast(StringType()).alias("prediction"), 
        col("Industry"), 
        col("Population"), 
        col("Right_MBR_INDV_BE_KEY").cast(StringType()).alias("Right_MBR_INDV_BE_KEY"), 
        col("OP"), 
        col("`class_1.0`").cast(StringType()).alias("class_1.0"), 
        col("`Household ED Visits`").alias("Household ED Visits"), 
        col("`Members in Household`").alias("Members in Household"), 
        col("row_id"), 
        col("`Household ED Visit Alw Amt`").cast(StringType()).alias("Household ED Visit Alw Amt"), 
        col("`ED Visits`").alias("ED Visits"), 
        col("IP"), 
        col("Last_Week"), 
        col("`class_0.0`").cast(StringType()).alias("class_0.0"), 
        col("`Drug Counts`").alias("Drug Counts"), 
        col("CountDistinct_Week"), 
        col("`Mental Health Claims`").alias("Mental Health Claims"), 
        col("`Historic Non Emergent Visit`").alias("Historic Non Emergent Visit"), 
        col("`Injury Related ED`").alias("Injury Related ED"), 
        col("`ED Visited`").alias("ED Visited"), 
        col("Claims"), 
        col("Relationship"), 
        col("`Drug Related ED`").alias("Drug Related ED"), 
        col("`Drug Classes`").alias("Drug Classes"), 
        col("Polypharmacy"), 
        col("Right_CountDistinct_Week"), 
        col("`Psych Related ED`").alias("Psych Related ED"), 
        col("`New Drugs`").alias("New Drugs"), 
        col("Gender"), 
        col("`Distance to Closest ED`").cast(StringType()).alias("Distance to Closest ED"), 
        col("Race"), 
        col("`Member Age`").alias("Member Age"), 
        col("`SPIRA Elligible`").alias("SPIRA Elligible"), 
        col("`Medical Home`").alias("Medical Home"), 
        col("`7-12 Month ED Visit History`").alias("7-12 Month ED Visit History"), 
        col("`ED Visit Tot Alw Amt`").cast(StringType()).alias("ED Visit Tot Alw Amt"), 
        col("`Alcohol Related ED`").alias("Alcohol Related ED"), 
        lit(None).cast(StringType()).alias("FREQUENT_FLYER")
    )
