from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def AlteryxSelect_3745(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("FNCL_LOB_CD"), 
        col("PROD_SH_NM_DLVRY_METH_CD"), 
        col("YEARMONTH"), 
        col("MBR_DSBLTY_IN"), 
        col("MBR_ENR_COBRA_IN"), 
        col("PROD_SH_NM"), 
        col("HOST_MBR_IN"), 
        col("YMD"), 
        col("EXPRNC_CAT_CD"), 
        col("FUND_CAT_CD"), 
        col("MBR_GNDR_CD"), 
        col("MBR_HOME_ADDR_ZIP_CD_5"), 
        col("PCP_FLAG"), 
        col("`High Deductible Ind`").alias("High Deductible Ind"), 
        col("MBR_INDV_BE_KEY"), 
        col("SPIRA_BNF_ID"), 
        col("SUB_MBR_SK"), 
        col("MBR_HOME_ADDR_ST_CD"), 
        col("CLS_PLN_DESC"), 
        col("PRNT_GRP_SIC_NACIS_CD"), 
        col("`Apt Ind`").alias("Apt Ind"), 
        col("FNCL_MKT_SEG_NM"), 
        col("GRP_MKT_SIZE_CAT_NM"), 
        col("`Retired With Blue`").alias("Retired With Blue"), 
        col("`Product Category`").alias("Product Category"), 
        col("MBR_RELSHP_NM"), 
        col("GRP_ZIP_CD_5"), 
        col("GRP_ID"), 
        col("`Target Forecasted`").alias("Target Forecasted"), 
        col("AGE"), 
        col("GRP_TOT_EMPL_CT"), 
        col("Avg_BCARE"), 
        col("Avg_BLUE_ACCESS"), 
        col("Avg_BLUE_SELECT"), 
        col("Avg_BLUESELECT_"), 
        col("Avg_HPEXTRNL"), 
        col("Avg_PC"), 
        col("Avg_PCB"), 
        col("Avg_PCBEXTRNL"), 
        col("`Spouse's Product`").alias("Spouse Retired"), 
        col("Members_on_Policy"), 
        col("`Spouse Age`").alias("Spouse Age"), 
        col("`Min_Dependent Age`").alias("Min_Dependent Age"), 
        col("`Male Percentage`").alias("Male Percentage"), 
        col("`Female Percentage`").alias("Female Percentage"), 
        col("`Average Age Males`").alias("Average Age Males"), 
        col("`Average Age Females`").alias("Average Age Females"), 
        col("SUM_CCI"), 
        col("`Member Months`").alias("Member Months"), 
        col("`Group Months`").alias("Group Months"), 
        col("`Drug Tier 1`").alias("Drug Tier 1"), 
        col("`Drug Tier 2`").alias("Drug Tier 2"), 
        col("`Drug Tier 3`").alias("Drug Tier 3"), 
        col("`Distinct NDC Codes`").alias("Distinct NDC Codes"), 
        col("`Distinct Diagnosis Types`").alias("Distinct Diagnosis Types"), 
        col("`Specialty Drug Counts`").alias("Specialty Drug Counts"), 
        col("`Generic Drug Counts`").alias("Generic Drug Counts"), 
        col("`Mail Order Drug Counts`").alias("Mail Order Drug Counts"), 
        col("`Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC`").alias("Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        col("`Vision EYE`").alias("Vision EYE"), 
        col("`Vision FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Vision FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Vision Member Pay`").alias("Vision Member Pay"), 
        col("`RX Member Pay`").alias("RX Member Pay"), 
        col("`Medical ALCOHOL_DRUG_USE_AND_DISORDERS`").alias("Medical ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        col("`Medical BLOOD_AND_BLOOD_FORMING_ORGANS`").alias("Medical BLOOD_AND_BLOOD_FORMING_ORGANS"), 
        col("`Medical BURNS`").alias("Medical BURNS"), 
        col("`Medical CIRCULATORY_SYSTEM`").alias("Medical CIRCULATORY_SYSTEM"), 
        col("`Medical DIGESTIVE_SYSTEM`").alias("Medical DIGESTIVE_SYSTEM"), 
        col("`Medical EAR__NOSE__AND_THROAT`").alias("Medical EAR__NOSE__AND_THROAT"), 
        col("`Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC`").alias("Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        col("`Medical EYE`").alias("Medical EYE"), 
        col("`Medical FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Medical FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Medical FEMALE_REPRODUCTIVE_SYSTEM`").alias("Medical FEMALE_REPRODUCTIVE_SYSTEM"), 
        col("`Medical HEPATOBILARY_SYSTEM`").alias("Medical HEPATOBILARY_SYSTEM"), 
        col("`Medical INFECTIOUS_AND_PARASITIC_DISEASES`").alias("Medical INFECTIOUS_AND_PARASITIC_DISEASES"), 
        col("`Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS`").alias("Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS"), 
        col("`Medical KIDNEY_AND_URINARY_TRACT`").alias("Medical KIDNEY_AND_URINARY_TRACT"), 
        col("`Medical MALE_REPRODUCTIVE_SYSTEM`").alias("Medical MALE_REPRODUCTIVE_SYSTEM"), 
        col("`Medical MENTAL_ILLNESS`").alias("Medical MENTAL_ILLNESS"), 
        col("`Medical MUSCULOSKETAL_SYSTEM`").alias("Medical MUSCULOSKETAL_SYSTEM"), 
        col("`Medical MYELOPROLIFERATIVE_AND_NEOPLASMS`").alias("Medical MYELOPROLIFERATIVE_AND_NEOPLASMS"), 
        col("`Medical NERVOUS_SYSTEM`").alias("Medical NERVOUS_SYSTEM"), 
        col("`Medical NEWBORNS_AND_OTHER_NEONATES`").alias("Medical NEWBORNS_AND_OTHER_NEONATES"), 
        col("`Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM`").alias("Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM"), 
        col("`Medical RESPIRATORY_SYSTEM`").alias("Medical RESPIRATORY_SYSTEM"), 
        col("`Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`").alias("Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        col("`Med Member Pay`").alias("Med Member Pay"), 
        col("`Medical AIDS_HIV`").alias("Medical AIDS_HIV"), 
        col("`Dental ALCOHOL_DRUG_USE_AND_DISORDERS`").alias("Dental ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        col("`Dental EAR__NOSE__AND_THROAT`").alias("Dental EAR__NOSE__AND_THROAT"), 
        col("`Dental FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Dental FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Dental MENTAL_ILLNESS`").alias("Dental MENTAL_ILLNESS"), 
        col("`Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`").alias("Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        col("`Dental Dental Member Pay`").alias("Dental Dental Member Pay"), 
        col("Emergency_Room"), 
        col("Inpatient"), 
        col("Outpatient"), 
        col("`Number of Winterizing Procedures`").alias("Number of Winterizing Procedures"), 
        col("`Dental Member Pay`").alias("Dental Member Pay"), 
        col("`Depression Related Claims`").alias("Depression Related Claims")
    )
