from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def DynamicRename_3760(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("MBR_INDV_BE_KEY"), 
        col("YEARMONTH"), 
        col("`Max_Average Age Females`").alias("Max_Average Age Females"), 
        col("Last_CLS_PLN_DESC").alias("CLS_PLN_DESC"), 
        col("`Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS`").alias("Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS"), 
        col("`Last_Product Category`").alias("Product Category"), 
        col("`Max_Group Months`").alias("Max_Group Months"), 
        col("`Medical FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Medical FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("Last_HOST_MBR_IN").alias("HOST_MBR_IN"), 
        col("`Max_Member Months`").alias("Max_Member Months"), 
        col("Last_GRP_MKT_SIZE_CAT_NM").alias("GRP_MKT_SIZE_CAT_NM"), 
        col("`Dental Member Pay`").alias("Dental Member Pay"), 
        col("`Vision Member Pay`").alias("Vision Member Pay"), 
        col("Last_Avg_BCARE").alias("Avg_BCARE"), 
        col("Max_SUM_CCI"), 
        col("`Depression Related Claims`").alias("Depression Related Claims"), 
        col("Last_GRP_ID").alias("GRP_ID"), 
        col("`Medical BURNS`").alias("Medical BURNS"), 
        col("`Last_High Deductible Ind`").alias("High Deductible Ind"), 
        col("YMD"), 
        col("Last_FNCL_LOB_CD").alias("FNCL_LOB_CD"), 
        col("`Drug Tier 3`").alias("Drug Tier 3"), 
        col("`Medical RESPIRATORY_SYSTEM`").alias("Medical RESPIRATORY_SYSTEM"), 
        col("`Med Member Pay`").alias("Med Member Pay"), 
        col("SUB_MBR_SK"), 
        col("`Number of Winterizing Procedures`").alias("Number of Winterizing Procedures"), 
        col("`Medical FEMALE_REPRODUCTIVE_SYSTEM`").alias("Medical FEMALE_REPRODUCTIVE_SYSTEM"), 
        col("Last_EXPRNC_CAT_CD").alias("EXPRNC_CAT_CD"), 
        col("`Medical MALE_REPRODUCTIVE_SYSTEM`").alias("Medical MALE_REPRODUCTIVE_SYSTEM"), 
        col("`Max_Apt Ind`").alias("Max_Apt Ind"), 
        col("Last_MBR_HOME_ADDR_ZIP_CD_5").alias("MBR_HOME_ADDR_ZIP_CD_5"), 
        col("`Max_Male Percentage`").alias("Max_Male Percentage"), 
        col("`Max_Spouse Age`").alias("Max_Spouse Age"), 
        col("`Medical AIDS_HIV`").alias("Medical AIDS_HIV"), 
        col("Last_Avg_PCBEXTRNL").alias("Avg_PCBEXTRNL"), 
        col("`Medical MENTAL_ILLNESS`").alias("Medical MENTAL_ILLNESS"), 
        col("`Last_Retired With Blue`").alias("Retired With Blue"), 
        col("`Medical KIDNEY_AND_URINARY_TRACT`").alias("Medical KIDNEY_AND_URINARY_TRACT"), 
        col("Last_AGE").alias("AGE"), 
        col("Last_PCP_FLAG").alias("PCP_FLAG"), 
        col("`Medical MYELOPROLIFERATIVE_AND_NEOPLASMS`").alias("Medical MYELOPROLIFERATIVE_AND_NEOPLASMS"), 
        col("Last_GRP_ZIP_CD_5").alias("GRP_ZIP_CD_5"), 
        col("`Dental MENTAL_ILLNESS`").alias("Dental MENTAL_ILLNESS"), 
        col("`Medical EAR__NOSE__AND_THROAT`").alias("Medical EAR__NOSE__AND_THROAT"), 
        col("`Medical BLOOD_AND_BLOOD_FORMING_ORGANS`").alias("Medical BLOOD_AND_BLOOD_FORMING_ORGANS"), 
        col("Last_Avg_BLUESELECT_").alias("Avg_BLUESELECT_"), 
        col("Last_MBR_DSBLTY_IN").alias("MBR_DSBLTY_IN"), 
        col("`Drug Tier 2`").alias("Drug Tier 2"), 
        col("`Generic Drug Counts`").alias("Generic Drug Counts"), 
        col("Outpatient"), 
        col("Max_GRP_TOT_EMPL_CT"), 
        col("`Max_Min_Dependent Age`").alias("Max_Min_Dependent Age"), 
        col("`Dental EAR__NOSE__AND_THROAT`").alias("Dental EAR__NOSE__AND_THROAT"), 
        col("Last_Avg_BLUE_SELECT").alias("Avg_BLUE_SELECT"), 
        col("`Specialty Drug Counts`").alias("Specialty Drug Counts"), 
        col("`Medical DIGESTIVE_SYSTEM`").alias("Medical DIGESTIVE_SYSTEM"), 
        col("Last_Avg_PC").alias("Avg_PC"), 
        col("`Max_Spouse Retired`").alias("Max_Spouse Retired"), 
        col("Inpatient"), 
        col("Last_MBR_ENR_COBRA_IN").alias("MBR_ENR_COBRA_IN"), 
        col("`Medical INFECTIOUS_AND_PARASITIC_DISEASES`").alias("Medical INFECTIOUS_AND_PARASITIC_DISEASES"), 
        col("`RX Member Pay`").alias("RX Member Pay"), 
        col("`Drug Tier 1`").alias("Drug Tier 1"), 
        col("`Dental FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Dental FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Vision EYE`").alias("Vision EYE"), 
        col("`Dental Dental Member Pay`").alias("Dental Dental Member Pay"), 
        col("`Vision FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Vision FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Distinct NDC Codes`").alias("Distinct NDC Codes"), 
        col("`Last_Target Forecasted`").alias("Target Forecasted"), 
        col("`Dental ALCOHOL_DRUG_USE_AND_DISORDERS`").alias("Dental ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        col("`Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC`").alias("Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        col("Last_MBR_HOME_ADDR_ST_CD").alias("MBR_HOME_ADDR_ST_CD"), 
        col("Last_MBR_RELSHP_NM").alias("MBR_RELSHP_NM"), 
        col("`Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`").alias("Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        col("`Distinct Diagnosis Types`").alias("Distinct Diagnosis Types"), 
        col("`Medical HEPATOBILARY_SYSTEM`").alias("Medical HEPATOBILARY_SYSTEM"), 
        col("Last_MBR_GNDR_CD").alias("MBR_GNDR_CD"), 
        col("Max_Members_on_Policy"), 
        col("`Mail Order Drug Counts`").alias("Mail Order Drug Counts"), 
        col("Last_SPIRA_BNF_ID").alias("SPIRA_BNF_ID"), 
        col("`Max_Female Percentage`").alias("Max_Female Percentage"), 
        col("`Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`").alias("Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        col("`Medical EYE`").alias("Medical EYE"), 
        col("Last_PRNT_GRP_SIC_NACIS_CD").alias("PRNT_GRP_SIC_NACIS_CD"), 
        col("Emergency_Room"), 
        col("`Medical ALCOHOL_DRUG_USE_AND_DISORDERS`").alias("Medical ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        col("Last_Avg_PCB").alias("Avg_PCB"), 
        col("`Medical MUSCULOSKETAL_SYSTEM`").alias("Medical MUSCULOSKETAL_SYSTEM"), 
        col("`Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC`").alias("Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        col("Last_Avg_BLUE_ACCESS").alias("Avg_BLUE_ACCESS"), 
        col("`Max_Average Age Males`").alias("Max_Average Age Males"), 
        col("`Medical NEWBORNS_AND_OTHER_NEONATES`").alias("Medical NEWBORNS_AND_OTHER_NEONATES"), 
        col("`Medical CIRCULATORY_SYSTEM`").alias("Medical CIRCULATORY_SYSTEM"), 
        col("`Medical NERVOUS_SYSTEM`").alias("Medical NERVOUS_SYSTEM"), 
        col("`Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM`").alias("Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM")
    )
