from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def DynamicRename_3761(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("MBR_INDV_BE_KEY"), 
        col("YEARMONTH"), 
        col("`Max_Average Age Females`").alias("Max_Average Age Females"), 
        col("`Sum_Distinct NDC Codes`").alias("Distinct NDC Codes"), 
        col("Last_CLS_PLN_DESC"), 
        col("`Last_Product Category`").alias("Last_Product Category"), 
        col("`Max_Group Months`").alias("Max_Group Months"), 
        col("Last_HOST_MBR_IN"), 
        col("`Max_Member Months`").alias("Max_Member Months"), 
        col("`Sum_Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS`")\
          .alias("Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS"), 
        col("`Sum_Medical NERVOUS_SYSTEM`").alias("Medical NERVOUS_SYSTEM"), 
        col("`Sum_Medical FEMALE_REPRODUCTIVE_SYSTEM`").alias("Medical FEMALE_REPRODUCTIVE_SYSTEM"), 
        col("`Sum_Mail Order Drug Counts`").alias("Mail Order Drug Counts"), 
        col("Last_GRP_MKT_SIZE_CAT_NM"), 
        col("`Sum_Distinct Diagnosis Types`").alias("Distinct Diagnosis Types"), 
        col("`Sum_Vision FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Vision FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Sum_Medical RESPIRATORY_SYSTEM`").alias("Medical RESPIRATORY_SYSTEM"), 
        col("Last_Avg_BCARE"), 
        col("Max_SUM_CCI"), 
        col("Last_GRP_ID"), 
        col("`Last_High Deductible Ind`").alias("Last_High Deductible Ind"), 
        col("YMD"), 
        col("Last_FNCL_LOB_CD"), 
        col("`Sum_Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`").alias("Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        col("`Sum_Dental ALCOHOL_DRUG_USE_AND_DISORDERS`").alias("Dental ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        col("`Sum_RX Member Pay`").alias("RX Member Pay"), 
        col("SUB_MBR_SK"), 
        col("`Sum_Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC`").alias("Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        col("Last_EXPRNC_CAT_CD"), 
        col("`Sum_Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC`").alias("Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        col("`Sum_Dental EAR__NOSE__AND_THROAT`").alias("Dental EAR__NOSE__AND_THROAT"), 
        col("`Max_Apt Ind`").alias("Max_Apt Ind"), 
        col("`Sum_Medical EYE`").alias("Medical EYE"), 
        col("`Sum_Medical BLOOD_AND_BLOOD_FORMING_ORGANS`").alias("Medical BLOOD_AND_BLOOD_FORMING_ORGANS"), 
        col("`Sum_Medical ALCOHOL_DRUG_USE_AND_DISORDERS`").alias("Medical ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        col("`Sum_Dental MENTAL_ILLNESS`").alias("Dental MENTAL_ILLNESS"), 
        col("Last_MBR_HOME_ADDR_ZIP_CD_5"), 
        col("`Max_Male Percentage`").alias("Max_Male Percentage"), 
        col("`Max_Spouse Age`").alias("Max_Spouse Age"), 
        col("`Sum_Number of Winterizing Procedures`").alias("Number of Winterizing Procedures"), 
        col("Last_Avg_PCBEXTRNL"), 
        col("`Last_Retired With Blue`").alias("Last_Retired With Blue"), 
        col("Last_AGE"), 
        col("`Sum_Specialty Drug Counts`").alias("Specialty Drug Counts"), 
        col("Last_PCP_FLAG"), 
        col("`Sum_Medical INFECTIOUS_AND_PARASITIC_DISEASES`").alias("Medical INFECTIOUS_AND_PARASITIC_DISEASES"), 
        col("`Sum_Depression Related Claims`").alias("Depression Related Claims"), 
        col("Last_GRP_ZIP_CD_5"), 
        col("`Sum_Dental Member Pay`").alias("Dental Member Pay"), 
        col("`Sum_Vision Member Pay`").alias("Vision Member Pay"), 
        col("`Sum_Medical HEPATOBILARY_SYSTEM`").alias("Medical HEPATOBILARY_SYSTEM"), 
        col("`Sum_Medical CIRCULATORY_SYSTEM`").alias("Medical CIRCULATORY_SYSTEM"), 
        col("Last_Avg_BLUESELECT_"), 
        col("`Sum_Medical AIDS_HIV`").alias("Medical AIDS_HIV"), 
        col("Last_MBR_DSBLTY_IN"), 
        col("Max_GRP_TOT_EMPL_CT"), 
        col("`Sum_Dental Dental Member Pay`").alias("Dental Dental Member Pay"), 
        col("`Max_Min_Dependent Age`").alias("Max_Min_Dependent Age"), 
        col("`Sum_Drug Tier 2`").alias("Drug Tier 2"), 
        col("Last_Avg_BLUE_SELECT"), 
        col("Last_Avg_PC"), 
        col("`Max_Spouse Retired`").alias("Max_Spouse Retired"), 
        col("Last_MBR_ENR_COBRA_IN"), 
        col("`Sum_Generic Drug Counts`").alias("Generic Drug Counts"), 
        col("`Sum_Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM`").alias("Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM"), 
        col("`Sum_Dental FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Dental FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Sum_Medical FACTORS_INFLUENCING_HEALTH_STATUS`").alias("Medical FACTORS_INFLUENCING_HEALTH_STATUS"), 
        col("`Sum_Medical BURNS`").alias("Medical BURNS"), 
        col("`Sum_Medical NEWBORNS_AND_OTHER_NEONATES`").alias("Medical NEWBORNS_AND_OTHER_NEONATES"), 
        col("`Sum_Medical MENTAL_ILLNESS`").alias("Medical MENTAL_ILLNESS"), 
        col("`Sum_Medical MALE_REPRODUCTIVE_SYSTEM`").alias("Medical MALE_REPRODUCTIVE_SYSTEM"), 
        col("Sum_Outpatient").alias("Outpatient"), 
        col("`Sum_Medical DIGESTIVE_SYSTEM`").alias("Medical DIGESTIVE_SYSTEM"), 
        col("`Last_Target Forecasted`").alias("Last_Target Forecasted"), 
        col("`Sum_Drug Tier 3`").alias("Drug Tier 3"), 
        col("Last_MBR_HOME_ADDR_ST_CD"), 
        col("Last_MBR_RELSHP_NM"), 
        col("`Sum_Drug Tier 1`").alias("Drug Tier 1"), 
        col("Last_MBR_GNDR_CD"), 
        col("Sum_Inpatient").alias("Inpatient"), 
        col("Max_Members_on_Policy"), 
        col("`Sum_Medical EAR__NOSE__AND_THROAT`").alias("Medical EAR__NOSE__AND_THROAT"), 
        col("`Sum_Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`").alias("Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        col("`Sum_Vision EYE`").alias("Vision EYE"), 
        col("`Sum_Medical KIDNEY_AND_URINARY_TRACT`").alias("Medical KIDNEY_AND_URINARY_TRACT"), 
        col("Last_SPIRA_BNF_ID"), 
        col("Sum_Emergency_Room").alias("Emergency_Room"), 
        col("`Sum_Medical MUSCULOSKETAL_SYSTEM`").alias("Medical MUSCULOSKETAL_SYSTEM"), 
        col("`Max_Female Percentage`").alias("Max_Female Percentage"), 
        col("`Sum_Med Member Pay`").alias("Med Member Pay"), 
        col("Last_PRNT_GRP_SIC_NACIS_CD"), 
        col("Last_Avg_PCB"), 
        col("Last_Avg_BLUE_ACCESS"), 
        col("`Max_Average Age Males`").alias("Max_Average Age Males"), 
        col("`Sum_Medical MYELOPROLIFERATIVE_AND_NEOPLASMS`").alias("Medical MYELOPROLIFERATIVE_AND_NEOPLASMS")
    )
