from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def Summarize_4258(spark: SparkSession, in0: DataFrame) -> DataFrame:
    df1 = in0.groupBy(col("MBR_INDV_BE_KEY"), col("SUB_MBR_SK"), col("YEARMONTH"), col("YMD"))

    return df1.agg(
        last(col("Avg_BLUE_ACCESS")).alias("Last_Avg_BLUE_ACCESS"), 
        sum(col("`Medical AIDS_HIV`")).alias("Sum_Medical AIDS_HIV"), 
        last(col("Avg_PCB")).alias("Last_Avg_PCB"), 
        max(col("`Apt Ind`")).alias("Max_Apt Ind"), 
        max(col("`Spouse Retired`")).alias("Max_Spouse Retired"), 
        sum(col("`Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC`"))\
          .alias("Sum_Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        sum(col("`Drug Tier 3`")).alias("Sum_Drug Tier 3"), 
        last(col("MBR_RELSHP_NM")).alias("Last_MBR_RELSHP_NM"), 
        sum(col("`Medical NEWBORNS_AND_OTHER_NEONATES`")).alias("Sum_Medical NEWBORNS_AND_OTHER_NEONATES"), 
        last(col("`High Deductible Ind`")).alias("Last_High Deductible Ind"), 
        last(col("GRP_ID")).alias("Last_GRP_ID"), 
        sum(col("`Distinct NDC Codes`")).alias("Sum_Distinct NDC Codes"), 
        sum(col("Outpatient")).alias("Sum_Outpatient"), 
        last(col("FNCL_LOB_CD")).alias("Last_FNCL_LOB_CD"), 
        max(col("`Spouse Age`")).alias("Max_Spouse Age"), 
        sum(col("`Dental EAR__NOSE__AND_THROAT`")).alias("Sum_Dental EAR__NOSE__AND_THROAT"), 
        last(col("GRP_ZIP_CD_5")).alias("Last_GRP_ZIP_CD_5"), 
        max(col("`Female Percentage`")).alias("Max_Female Percentage"), 
        sum(col("`Vision EYE`")).alias("Sum_Vision EYE"), 
        last(col("Avg_BLUE_SELECT")).alias("Last_Avg_BLUE_SELECT"), 
        last(col("Avg_BCARE")).alias("Last_Avg_BCARE"), 
        last(col("`Retired With Blue`")).alias("Last_Retired With Blue"), 
        sum(col("`Drug Tier 2`")).alias("Sum_Drug Tier 2"), 
        last(col("MBR_DSBLTY_IN")).alias("Last_MBR_DSBLTY_IN"), 
        max(col("`Average Age Females`")).alias("Max_Average Age Females"), 
        sum(col("`Dental Dental Member Pay`")).alias("Sum_Dental Dental Member Pay"), 
        sum(col("`Medical HEPATOBILARY_SYSTEM`")).alias("Sum_Medical HEPATOBILARY_SYSTEM"), 
        last(col("MBR_GNDR_CD")).alias("Last_MBR_GNDR_CD"), 
        sum(col("`Medical MYELOPROLIFERATIVE_AND_NEOPLASMS`")).alias("Sum_Medical MYELOPROLIFERATIVE_AND_NEOPLASMS"), 
        sum(col("`Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`"))\
          .alias("Sum_Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        sum(col("`Dental ALCOHOL_DRUG_USE_AND_DISORDERS`")).alias("Sum_Dental ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        sum(col("`Number of Winterizing Procedures`")).alias("Sum_Number of Winterizing Procedures"), 
        last(col("`Product Category`")).alias("Last_Product Category"), 
        sum(col("`Distinct Diagnosis Types`")).alias("Sum_Distinct Diagnosis Types"), 
        sum(col("`Medical FACTORS_INFLUENCING_HEALTH_STATUS`")).alias("Sum_Medical FACTORS_INFLUENCING_HEALTH_STATUS"), 
        last(col("Avg_BLUESELECT_")).alias("Last_Avg_BLUESELECT_"), 
        sum(col("`Medical DIGESTIVE_SYSTEM`")).alias("Sum_Medical DIGESTIVE_SYSTEM"), 
        last(col("SPIRA_BNF_ID")).alias("Last_SPIRA_BNF_ID"), 
        sum(col("`Medical BURNS`")).alias("Sum_Medical BURNS"), 
        max(col("`Member Months`")).alias("Max_Member Months"), 
        sum(col("`Dental Member Pay`")).alias("Sum_Dental Member Pay"), 
        sum(col("`Medical BLOOD_AND_BLOOD_FORMING_ORGANS`")).alias("Sum_Medical BLOOD_AND_BLOOD_FORMING_ORGANS"), 
        max(col("`Group Months`")).alias("Max_Group Months"), 
        sum(col("Inpatient")).alias("Sum_Inpatient"), 
        last(col("PRNT_GRP_SIC_NACIS_CD")).alias("Last_PRNT_GRP_SIC_NACIS_CD"), 
        sum(col("`Medical EAR__NOSE__AND_THROAT`")).alias("Sum_Medical EAR__NOSE__AND_THROAT"), 
        sum(col("`Drug Tier 1`")).alias("Sum_Drug Tier 1"), 
        last(col("PCP_FLAG")).alias("Last_PCP_FLAG"), 
        sum(col("`Depression Related Claims`")).alias("Sum_Depression Related Claims"), 
        sum(col("`Medical NERVOUS_SYSTEM`")).alias("Sum_Medical NERVOUS_SYSTEM"), 
        sum(col("`Generic Drug Counts`")).alias("Sum_Generic Drug Counts"), 
        max(col("SUM_CCI")).alias("Max_SUM_CCI"), 
        sum(col("`Medical MUSCULOSKETAL_SYSTEM`")).alias("Sum_Medical MUSCULOSKETAL_SYSTEM"), 
        last(col("MBR_ENR_COBRA_IN")).alias("Last_MBR_ENR_COBRA_IN"), 
        max(col("`Male Percentage`")).alias("Max_Male Percentage"), 
        max(col("`Average Age Males`")).alias("Max_Average Age Males"), 
        sum(col("`Dental MENTAL_ILLNESS`")).alias("Sum_Dental MENTAL_ILLNESS"), 
        max(col("Members_on_Policy")).alias("Max_Members_on_Policy"), 
        sum(col("`Medical MALE_REPRODUCTIVE_SYSTEM`")).alias("Sum_Medical MALE_REPRODUCTIVE_SYSTEM"), 
        last(col("HOST_MBR_IN")).alias("Last_HOST_MBR_IN"), 
        sum(col("`Medical FEMALE_REPRODUCTIVE_SYSTEM`")).alias("Sum_Medical FEMALE_REPRODUCTIVE_SYSTEM"), 
        sum(col("`Medical EYE`")).alias("Sum_Medical EYE"), 
        last(col("AGE")).alias("Last_AGE"), 
        max(col("GRP_TOT_EMPL_CT")).alias("Max_GRP_TOT_EMPL_CT"), 
        sum(col("`Medical ALCOHOL_DRUG_USE_AND_DISORDERS`")).alias("Sum_Medical ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        last(col("GRP_MKT_SIZE_CAT_NM")).alias("Last_GRP_MKT_SIZE_CAT_NM"), 
        sum(col("`Med Member Pay`")).alias("Sum_Med Member Pay"), 
        sum(col("`Medical CIRCULATORY_SYSTEM`")).alias("Sum_Medical CIRCULATORY_SYSTEM"), 
        sum(col("`Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST`")).alias("Sum_Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        sum(col("`Mail Order Drug Counts`")).alias("Sum_Mail Order Drug Counts"), 
        max(col("`Min_Dependent Age`")).alias("Max_Min_Dependent Age"), 
        sum(col("`Dental FACTORS_INFLUENCING_HEALTH_STATUS`")).alias("Sum_Dental FACTORS_INFLUENCING_HEALTH_STATUS"), 
        last(col("Avg_PCBEXTRNL")).alias("Last_Avg_PCBEXTRNL"), 
        sum(col("`Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM`"))\
          .alias("Sum_Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM"), 
        last(col("CLS_PLN_DESC")).alias("Last_CLS_PLN_DESC"), 
        sum(col("`Medical RESPIRATORY_SYSTEM`")).alias("Sum_Medical RESPIRATORY_SYSTEM"), 
        sum(col("`Vision Member Pay`")).alias("Sum_Vision Member Pay"), 
        last(col("MBR_HOME_ADDR_ST_CD")).alias("Last_MBR_HOME_ADDR_ST_CD"), 
        sum(col("`Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS`"))\
          .alias("Sum_Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS"), 
        sum(col("`Specialty Drug Counts`")).alias("Sum_Specialty Drug Counts"), 
        sum(col("`RX Member Pay`")).alias("Sum_RX Member Pay"), 
        sum(col("`Vision FACTORS_INFLUENCING_HEALTH_STATUS`")).alias("Sum_Vision FACTORS_INFLUENCING_HEALTH_STATUS"), 
        sum(col("`Medical INFECTIOUS_AND_PARASITIC_DISEASES`")).alias("Sum_Medical INFECTIOUS_AND_PARASITIC_DISEASES"), 
        sum(col("`Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC`"))\
          .alias("Sum_Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        sum(col("Emergency_Room")).alias("Sum_Emergency_Room"), 
        last(col("EXPRNC_CAT_CD")).alias("Last_EXPRNC_CAT_CD"), 
        sum(col("`Medical MENTAL_ILLNESS`")).alias("Sum_Medical MENTAL_ILLNESS"), 
        last(col("`Target Forecasted`")).alias("Last_Target Forecasted"), 
        last(col("MBR_HOME_ADDR_ZIP_CD_5")).alias("Last_MBR_HOME_ADDR_ZIP_CD_5"), 
        last(col("Avg_PC")).alias("Last_Avg_PC"), 
        sum(col("`Medical KIDNEY_AND_URINARY_TRACT`")).alias("Sum_Medical KIDNEY_AND_URINARY_TRACT")
    )
