from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def Union_2526_reformat_0(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        col("YEARMONTH"), 
        col("`Female Percentage`").alias("Female Percentage"), 
        col("MBR_INDV_BE_KEY"), 
        col("MBR_RELSHP_NM"), 
        col("`Average Age Males`").alias("Average Age Males"), 
        col("`Target Forecasted`").alias("Target Forecasted"), 
        col("Avg_PCB"), 
        col("Avg_BCARE"), 
        col("MBR_SK"), 
        col("Avg_HPEXTRNL"), 
        col("YMD"), 
        col("`Retired With Blue`").alias("Retired With Blue"), 
        col("`Male Percentage`").alias("Male Percentage"), 
        col("`Marketing Restricted`").alias("Marketing Restricted"), 
        col("Avg_BLUESELECT_"), 
        col("SUB_MBR_SK"), 
        col("`Switch to Retirement`").alias("Switch to Retirement"), 
        col("`Spouse Age`").alias("Spouse Age"), 
        col("MBR_FIRST_NM"), 
        col("MBR_HOME_ADDR_LN_2"), 
        col("MBR_HOME_ADDR_ZIP_CD_5"), 
        col("`Recent Mover`").alias("Recent Mover"), 
        col("PCP_FLAG"), 
        col("`Spouse's Product`").alias("Spouse's Product"), 
        col("`Min_Dependent Age`").alias("Min_Dependent Age"), 
        col("GRP_NM"), 
        col("GRP_ID"), 
        col("GRP_BILL_LVL_NM"), 
        col("Avg_PC"), 
        col("HOST_MBR_IN"), 
        col("AGE"), 
        col("MBR_DSBLTY_IN"), 
        col("EXPRNC_CAT_CD"), 
        col("FUND_CAT_CD"), 
        col("CLS_PLN_DESC"), 
        col("PROD_SH_NM_DLVRY_METH_CD"), 
        col("Members_on_Policy"), 
        col("SUM_CCI"), 
        col("`Retiree in Household Indicator`").alias("Retiree in Household Indicator"), 
        col("PROD_SH_NM"), 
        col("GRP_TOT_EMPL_CT"), 
        col("SPIRA_BNF_ID"), 
        col("MBR_GNDR_CD"), 
        col("`Member Months`").alias("Member Months"), 
        col("MBR_ENR_COBRA_IN"), 
        col("MBR_HOME_ADDR_LN_1"), 
        col("`Average Age Females`").alias("Average Age Females"), 
        col("`Product Category`").alias("Product Category"), 
        col("Avg_BLUE_SELECT"), 
        col("GRP_MKT_SIZE_CAT_NM"), 
        col("MBR_LAST_NM"), 
        col("Product"), 
        col("`Group Months`").alias("Group Months"), 
        col("PRNT_GRP_SIC_NACIS_CD"), 
        col("MBR_HOME_ADDR_ST_CD"), 
        col("FNCL_LOB_CD"), 
        col("FNCL_MKT_SEG_NM"), 
        col("Retire"), 
        col("GRP_SK"), 
        col("GRP_ZIP_CD_5"), 
        col("MBR_UNIQ_KEY"), 
        col("Avg_BLUE_ACCESS"), 
        col("Avg_PCBEXTRNL"), 
        col("GRP_BUS_SUB_CAT_SH_NM"), 
        col("`Product Counter`").alias("Product Counter"), 
        lit(None).cast(DoubleType()).alias("Medical INJURIES__POISONINGS_AND_DRUG_EFFECTS"), 
        lit(None).cast(DoubleType()).alias("Medical FACTORS_INFLUENCING_HEALTH_STATUS"), 
        lit(None).cast(DoubleType()).alias("Vision Member Pay"), 
        lit(None).cast(DoubleType()).alias("Unkown Drug Tier"), 
        lit(None).cast(DoubleType()).alias("Medical BURNS"), 
        lit(None).cast(DoubleType()).alias("Drug Tier 3"), 
        lit(None).cast(DoubleType()).alias("Medical RESPIRATORY_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Med Member Pay"), 
        lit(None).cast(StringType()).alias("Dental Received Date"), 
        lit(None).cast(DoubleType()).alias("Medical FEMALE_REPRODUCTIVE_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Dental EYE"), 
        lit(None).cast(DoubleType()).alias("Medical MALE_REPRODUCTIVE_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Medical NOT_APPLICABLE"), 
        lit(None).cast(DoubleType()).alias("Medical AIDS_HIV"), 
        lit(None).cast(DoubleType()).alias("Medical MENTAL_ILLNESS"), 
        lit(None).cast(DoubleType()).alias("Medical KIDNEY_AND_URINARY_TRACT"), 
        lit(None).cast(DoubleType()).alias("Medical MYELOPROLIFERATIVE_AND_NEOPLASMS"), 
        lit(None).cast(DoubleType()).alias("Dental MENTAL_ILLNESS"), 
        lit(None).cast(DoubleType()).alias("Medical EAR__NOSE__AND_THROAT"), 
        lit(None).cast(DoubleType()).alias("Medical BLOOD_AND_BLOOD_FORMING_ORGANS"), 
        lit(None).cast(DoubleType()).alias("Drug Tier 2"), 
        lit(None).cast(StringType()).alias("Medical Received Date"), 
        lit(None).cast(DoubleType()).alias("Generic Drug Counts"), 
        lit(None).cast(DoubleType()).alias("Dental EAR__NOSE__AND_THROAT"), 
        lit(None).cast(DoubleType()).alias("Medical NO_DIAGNOSTIC_CATEGORY"), 
        lit(None).cast(DoubleType()).alias("Specialty Drug Counts"), 
        lit(None).cast(DoubleType()).alias("Medical DIGESTIVE_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Dental NO_DIAGNOSTIC_CATEGORY"), 
        lit(None).cast(DoubleType()).alias("Medical INFECTIOUS_AND_PARASITIC_DISEASES"), 
        lit(None).cast(DoubleType()).alias("RX Member Pay"), 
        lit(None).cast(DoubleType()).alias("Drug Tier 1"), 
        lit(None).cast(DoubleType()).alias("Dental FACTORS_INFLUENCING_HEALTH_STATUS"), 
        lit(None).cast(DoubleType()).alias("Vision EYE"), 
        lit(None).cast(DoubleType()).alias("Medical UNKNOWN"), 
        lit(None).cast(DoubleType()).alias("Dental Dental Member Pay"), 
        lit(None).cast(DoubleType()).alias("Vision FACTORS_INFLUENCING_HEALTH_STATUS"), 
        lit(None).cast(StringType()).alias("Distinct NDC Codes"), 
        lit(None).cast(DoubleType()).alias("Dental NOT_APPLICABLE"), 
        lit(None).cast(DoubleType()).alias("Dental ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        lit(None).cast(DoubleType()).alias("Medical ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        lit(None).cast(DoubleType()).alias("Medical SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        lit(None).cast(StringType()).alias("Distinct Diagnosis Types"), 
        lit(None).cast(DoubleType()).alias("Medical HEPATOBILARY_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Mail Order Drug Counts"), 
        lit(None).cast(DoubleType()).alias("Vision NO_DIAGNOSTIC_CATEGORY"), 
        lit(None).cast(DoubleType()).alias("Dental SKIN_SUBCUTANEOUS_TISSUE_AND_BREAST"), 
        lit(None).cast(DoubleType()).alias("Medical EYE"), 
        lit(None).cast(DoubleType()).alias("Medical ALCOHOL_DRUG_USE_AND_DISORDERS"), 
        lit(None).cast(DoubleType()).alias("Medical MUSCULOSKETAL_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Vision ENDOCRINE__NUTRITIONAL_AND_METABOLIC"), 
        lit(None).cast(DoubleType()).alias("Medical NEWBORNS_AND_OTHER_NEONATES"), 
        lit(None).cast(DoubleType()).alias("Medical CIRCULATORY_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Medical NERVOUS_SYSTEM"), 
        lit(None).cast(DoubleType()).alias("Medical PREGNANCY__CHILDBIRTH_AND_PUERPERIUM")
    )
