package io.prophecy.pipelines.perf_pipeline.graph

import io.prophecy.libs._
import io.prophecy.pipelines.perf_pipeline.udfs.PipelineInitCode._
import io.prophecy.pipelines.perf_pipeline.udfs.UDFs._
import io.prophecy.pipelines.perf_pipeline.config.Context
import org.apache.spark._
import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import org.apache.spark.sql.expressions._
import java.time._

object Reformat_1 {

  def apply(context: Context, in: DataFrame): DataFrame =
    in.select(
      col("id"),
      col("id1").as("id0"),
      col("id"),
      col("id0"),
      col("id1"),
      col("id2"),
      col("id3"),
      col("id4"),
      col("id5"),
      col("id6"),
      col("id7"),
      col("id8"),
      col("id9"),
      col("id10"),
      col("id11"),
      col("id12"),
      col("id13"),
      col("id14"),
      col("id15"),
      col("id16"),
      col("id17"),
      col("id18"),
      col("id19"),
      col("id20"),
      col("id21"),
      col("id22"),
      col("id23"),
      col("id24"),
      col("id25"),
      col("id26"),
      col("id27"),
      col("id28"),
      col("id29"),
      col("id30"),
      col("id31"),
      col("id32"),
      col("id33"),
      col("id34"),
      col("id35"),
      col("id36"),
      col("id37"),
      col("id38"),
      col("id39"),
      col("id40"),
      col("id41"),
      col("id42"),
      col("id43"),
      col("id44"),
      col("id45"),
      col("id46"),
      col("id47"),
      col("id48"),
      col("id49"),
      col("id50"),
      col("id51"),
      col("id52"),
      col("id53"),
      col("id54"),
      col("id55"),
      col("id56"),
      col("id57"),
      col("id58"),
      col("id59"),
      col("id60"),
      col("id61"),
      col("id62"),
      col("id63"),
      col("id64"),
      col("id65"),
      col("id66"),
      col("id67"),
      col("id68"),
      col("id69"),
      col("id70"),
      col("id71"),
      col("id72"),
      col("id73"),
      col("id74"),
      col("id75"),
      col("id76"),
      col("id77"),
      col("id78"),
      col("id79"),
      col("id80"),
      col("id81"),
      col("id82"),
      col("id83"),
      col("id84"),
      col("id85"),
      col("id86"),
      col("id87"),
      col("id88"),
      col("id89"),
      col("id90"),
      col("id91"),
      col("id92"),
      col("id93"),
      col("id94")
    )

}
