from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def MultiFieldFormula_760(spark: SparkSession, in0: DataFrame) -> DataFrame:
    return in0.select(
        when(col("CCI").isNull(), lit(0)).otherwise(col("CCI")).alias("CCI"), 
        when(col("CCI_6MoSum").isNull(), lit(0)).otherwise(col("CCI_6MoSum")).alias("CCI_6MoSum"), 
        when(col("CCI_Growth").isNull(), lit(0)).otherwise(col("CCI_Growth")).alias("CCI_Growth"), 
        when(col("IP_Month_Number").isNull(), lit(0)).otherwise(col("IP_Month_Number")).alias("IP_Month_Number"), 
        when(col("LowestGFR_Running3").isNull(), lit(0))\
          .otherwise(col("LowestGFR_Running3"))\
          .alias("LowestGFR_Running3"), 
        when(col("HighestAlbumin_Running3").isNull(), lit(0))\
          .otherwise(col("HighestAlbumin_Running3"))\
          .alias("HighestAlbumin_Running3"), 
        when(col("UniqueLabs_Running3").isNull(), lit(0))\
          .otherwise(col("UniqueLabs_Running3"))\
          .alias("UniqueLabs_Running3"), 
        when(col("CountOfLabs_Running3").isNull(), lit(0))\
          .otherwise(col("CountOfLabs_Running3"))\
          .alias("CountOfLabs_Running3"), 
        when(col("E00").isNull(), lit(0)).otherwise(col("E00")).alias("E00"), 
        when(col("E01").isNull(), lit(0)).otherwise(col("E01")).alias("E01"), 
        when(col("E02").isNull(), lit(0)).otherwise(col("E02")).alias("E02"), 
        when(col("E03").isNull(), lit(0)).otherwise(col("E03")).alias("E03"), 
        when(col("E04").isNull(), lit(0)).otherwise(col("E04")).alias("E04"), 
        when(col("E05").isNull(), lit(0)).otherwise(col("E05")).alias("E05"), 
        when(col("E06").isNull(), lit(0)).otherwise(col("E06")).alias("E06"), 
        when(col("E07").isNull(), lit(0)).otherwise(col("E07")).alias("E07"), 
        when(col("E08").isNull(), lit(0)).otherwise(col("E08")).alias("E08"), 
        when(col("E09").isNull(), lit(0)).otherwise(col("E09")).alias("E09"), 
        when(col("E10").isNull(), lit(0)).otherwise(col("E10")).alias("E10"), 
        when(col("E11").isNull(), lit(0)).otherwise(col("E11")).alias("E11"), 
        when(col("E13").isNull(), lit(0)).otherwise(col("E13")).alias("E13"), 
        when(col("E15").isNull(), lit(0)).otherwise(col("E15")).alias("E15"), 
        when(col("E16").isNull(), lit(0)).otherwise(col("E16")).alias("E16"), 
        when(col("E20").isNull(), lit(0)).otherwise(col("E20")).alias("E20"), 
        when(col("E21").isNull(), lit(0)).otherwise(col("E21")).alias("E21"), 
        when(col("E22").isNull(), lit(0)).otherwise(col("E22")).alias("E22"), 
        when(col("E23").isNull(), lit(0)).otherwise(col("E23")).alias("E23"), 
        when(col("E24").isNull(), lit(0)).otherwise(col("E24")).alias("E24"), 
        when(col("E25").isNull(), lit(0)).otherwise(col("E25")).alias("E25"), 
        when(col("E26").isNull(), lit(0)).otherwise(col("E26")).alias("E26"), 
        when(col("E27").isNull(), lit(0)).otherwise(col("E27")).alias("E27"), 
        when(col("E28").isNull(), lit(0)).otherwise(col("E28")).alias("E28"), 
        when(col("E29").isNull(), lit(0)).otherwise(col("E29")).alias("E29"), 
        when(col("E30").isNull(), lit(0)).otherwise(col("E30")).alias("E30"), 
        when(col("E31").isNull(), lit(0)).otherwise(col("E31")).alias("E31"), 
        when(col("E32").isNull(), lit(0)).otherwise(col("E32")).alias("E32"), 
        when(col("E34").isNull(), lit(0)).otherwise(col("E34")).alias("E34"), 
        when(col("E35").isNull(), lit(0)).otherwise(col("E35")).alias("E35"), 
        when(col("E36").isNull(), lit(0)).otherwise(col("E36")).alias("E36"), 
        when(col("E40").isNull(), lit(0)).otherwise(col("E40")).alias("E40"), 
        when(col("E41").isNull(), lit(0)).otherwise(col("E41")).alias("E41"), 
        when(col("E42").isNull(), lit(0)).otherwise(col("E42")).alias("E42"), 
        when(col("E43").isNull(), lit(0)).otherwise(col("E43")).alias("E43"), 
        when(col("E44").isNull(), lit(0)).otherwise(col("E44")).alias("E44"), 
        when(col("E45").isNull(), lit(0)).otherwise(col("E45")).alias("E45"), 
        when(col("E46").isNull(), lit(0)).otherwise(col("E46")).alias("E46"), 
        when(col("E50").isNull(), lit(0)).otherwise(col("E50")).alias("E50"), 
        when(col("E51").isNull(), lit(0)).otherwise(col("E51")).alias("E51"), 
        when(col("E52").isNull(), lit(0)).otherwise(col("E52")).alias("E52"), 
        when(col("E53").isNull(), lit(0)).otherwise(col("E53")).alias("E53"), 
        when(col("E54").isNull(), lit(0)).otherwise(col("E54")).alias("E54"), 
        when(col("E55").isNull(), lit(0)).otherwise(col("E55")).alias("E55"), 
        when(col("E56").isNull(), lit(0)).otherwise(col("E56")).alias("E56"), 
        when(col("E58").isNull(), lit(0)).otherwise(col("E58")).alias("E58"), 
        when(col("E59").isNull(), lit(0)).otherwise(col("E59")).alias("E59"), 
        when(col("E60").isNull(), lit(0)).otherwise(col("E60")).alias("E60"), 
        when(col("E61").isNull(), lit(0)).otherwise(col("E61")).alias("E61"), 
        when(col("E63").isNull(), lit(0)).otherwise(col("E63")).alias("E63"), 
        when(col("E64").isNull(), lit(0)).otherwise(col("E64")).alias("E64"), 
        when(col("E65").isNull(), lit(0)).otherwise(col("E65")).alias("E65"), 
        when(col("E66").isNull(), lit(0)).otherwise(col("E66")).alias("E66"), 
        when(col("E67").isNull(), lit(0)).otherwise(col("E67")).alias("E67"), 
        when(col("E68").isNull(), lit(0)).otherwise(col("E68")).alias("E68"), 
        when(col("E70").isNull(), lit(0)).otherwise(col("E70")).alias("E70"), 
        when(col("E71").isNull(), lit(0)).otherwise(col("E71")).alias("E71"), 
        when(col("E72").isNull(), lit(0)).otherwise(col("E72")).alias("E72"), 
        when(col("E73").isNull(), lit(0)).otherwise(col("E73")).alias("E73"), 
        when(col("E74").isNull(), lit(0)).otherwise(col("E74")).alias("E74"), 
        when(col("E75").isNull(), lit(0)).otherwise(col("E75")).alias("E75"), 
        when(col("E76").isNull(), lit(0)).otherwise(col("E76")).alias("E76"), 
        when(col("E77").isNull(), lit(0)).otherwise(col("E77")).alias("E77"), 
        when(col("E78").isNull(), lit(0)).otherwise(col("E78")).alias("E78"), 
        when(col("E79").isNull(), lit(0)).otherwise(col("E79")).alias("E79"), 
        when(col("E80").isNull(), lit(0)).otherwise(col("E80")).alias("E80"), 
        when(col("E83").isNull(), lit(0)).otherwise(col("E83")).alias("E83"), 
        when(col("E84").isNull(), lit(0)).otherwise(col("E84")).alias("E84"), 
        when(col("E85").isNull(), lit(0)).otherwise(col("E85")).alias("E85"), 
        when(col("E86").isNull(), lit(0)).otherwise(col("E86")).alias("E86"), 
        when(col("E87").isNull(), lit(0)).otherwise(col("E87")).alias("E87"), 
        when(col("E88").isNull(), lit(0)).otherwise(col("E88")).alias("E88"), 
        when(col("E89").isNull(), lit(0)).otherwise(col("E89")).alias("E89"), 
        when(col("F30").isNull(), lit(0)).otherwise(col("F30")).alias("F30"), 
        when(col("F31").isNull(), lit(0)).otherwise(col("F31")).alias("F31"), 
        when(col("F32").isNull(), lit(0)).otherwise(col("F32")).alias("F32"), 
        when(col("F33").isNull(), lit(0)).otherwise(col("F33")).alias("F33"), 
        when(col("F34").isNull(), lit(0)).otherwise(col("F34")).alias("F34"), 
        when(col("F39").isNull(), lit(0)).otherwise(col("F39")).alias("F39"), 
        when(col("M1A").isNull(), lit(0)).otherwise(col("M1A")).alias("M1A"), 
        when(col("M10").isNull(), lit(0)).otherwise(col("M10")).alias("M10"), 
        when(col("M11").isNull(), lit(0)).otherwise(col("M11")).alias("M11"), 
        when(col("M12").isNull(), lit(0)).otherwise(col("M12")).alias("M12"), 
        when(col("M13").isNull(), lit(0)).otherwise(col("M13")).alias("M13"), 
        when(col("M14").isNull(), lit(0)).otherwise(col("M14")).alias("M14"), 
        when(col("M15").isNull(), lit(0)).otherwise(col("M15")).alias("M15"), 
        when(col("M16").isNull(), lit(0)).otherwise(col("M16")).alias("M16"), 
        when(col("M17").isNull(), lit(0)).otherwise(col("M17")).alias("M17"), 
        when(col("M18").isNull(), lit(0)).otherwise(col("M18")).alias("M18"), 
        when(col("M19").isNull(), lit(0)).otherwise(col("M19")).alias("M19"), 
        when(col("M40").isNull(), lit(0)).otherwise(col("M40")).alias("M40"), 
        when(col("M41").isNull(), lit(0)).otherwise(col("M41")).alias("M41"), 
        when(col("M42").isNull(), lit(0)).otherwise(col("M42")).alias("M42"), 
        when(col("M43").isNull(), lit(0)).otherwise(col("M43")).alias("M43"), 
        when(col("M45").isNull(), lit(0)).otherwise(col("M45")).alias("M45"), 
        when(col("M46").isNull(), lit(0)).otherwise(col("M46")).alias("M46"), 
        when(col("M47").isNull(), lit(0)).otherwise(col("M47")).alias("M47"), 
        when(col("M48").isNull(), lit(0)).otherwise(col("M48")).alias("M48"), 
        when(col("M49").isNull(), lit(0)).otherwise(col("M49")).alias("M49"), 
        when(col("O00").isNull(), lit(0)).otherwise(col("O00")).alias("O00"), 
        when(col("O01").isNull(), lit(0)).otherwise(col("O01")).alias("O01"), 
        when(col("O02").isNull(), lit(0)).otherwise(col("O02")).alias("O02"), 
        when(col("O03").isNull(), lit(0)).otherwise(col("O03")).alias("O03"), 
        when(col("O04").isNull(), lit(0)).otherwise(col("O04")).alias("O04"), 
        when(col("O07").isNull(), lit(0)).otherwise(col("O07")).alias("O07"), 
        when(col("O08").isNull(), lit(0)).otherwise(col("O08")).alias("O08"), 
        when(col("O09").isNull(), lit(0)).otherwise(col("O09")).alias("O09"), 
        when(col("O20").isNull(), lit(0)).otherwise(col("O20")).alias("O20"), 
        when(col("O21").isNull(), lit(0)).otherwise(col("O21")).alias("O21"), 
        when(col("O22").isNull(), lit(0)).otherwise(col("O22")).alias("O22"), 
        when(col("O23").isNull(), lit(0)).otherwise(col("O23")).alias("O23"), 
        when(col("O24").isNull(), lit(0)).otherwise(col("O24")).alias("O24"), 
        when(col("O25").isNull(), lit(0)).otherwise(col("O25")).alias("O25"), 
        when(col("O26").isNull(), lit(0)).otherwise(col("O26")).alias("O26"), 
        when(col("O28").isNull(), lit(0)).otherwise(col("O28")).alias("O28"), 
        when(col("O29").isNull(), lit(0)).otherwise(col("O29")).alias("O29"), 
        when(col("O30").isNull(), lit(0)).otherwise(col("O30")).alias("O30"), 
        when(col("O31").isNull(), lit(0)).otherwise(col("O31")).alias("O31"), 
        when(col("O32").isNull(), lit(0)).otherwise(col("O32")).alias("O32"), 
        when(col("O33").isNull(), lit(0)).otherwise(col("O33")).alias("O33"), 
        when(col("O34").isNull(), lit(0)).otherwise(col("O34")).alias("O34"), 
        when(col("O35").isNull(), lit(0)).otherwise(col("O35")).alias("O35"), 
        when(col("O36").isNull(), lit(0)).otherwise(col("O36")).alias("O36"), 
        when(col("R10").isNull(), lit(0)).otherwise(col("R10")).alias("R10"), 
        when(col("R11").isNull(), lit(0)).otherwise(col("R11")).alias("R11"), 
        when(col("R12").isNull(), lit(0)).otherwise(col("R12")).alias("R12"), 
        when(col("R13").isNull(), lit(0)).otherwise(col("R13")).alias("R13"), 
        when(col("R14").isNull(), lit(0)).otherwise(col("R14")).alias("R14"), 
        when(col("R15").isNull(), lit(0)).otherwise(col("R15")).alias("R15"), 
        when(col("R16").isNull(), lit(0)).otherwise(col("R16")).alias("R16"), 
        when(col("R17").isNull(), lit(0)).otherwise(col("R17")).alias("R17"), 
        when(col("R18").isNull(), lit(0)).otherwise(col("R18")).alias("R18"), 
        when(col("R19").isNull(), lit(0)).otherwise(col("R19")).alias("R19"), 
        when(col("Z00").isNull(), lit(0)).otherwise(col("Z00")).alias("Z00"), 
        when(col("Z01").isNull(), lit(0)).otherwise(col("Z01")).alias("Z01"), 
        when(col("Z02").isNull(), lit(0)).otherwise(col("Z02")).alias("Z02"), 
        when(col("Z3A").isNull(), lit(0)).otherwise(col("Z3A")).alias("Z3A"), 
        when(col("Z03").isNull(), lit(0)).otherwise(col("Z03")).alias("Z03"), 
        when(col("Z04").isNull(), lit(0)).otherwise(col("Z04")).alias("Z04"), 
        when(col("Z05").isNull(), lit(0)).otherwise(col("Z05")).alias("Z05"), 
        when(col("Z08").isNull(), lit(0)).otherwise(col("Z08")).alias("Z08"), 
        when(col("Z09").isNull(), lit(0)).otherwise(col("Z09")).alias("Z09"), 
        when(col("Z11").isNull(), lit(0)).otherwise(col("Z11")).alias("Z11"), 
        when(col("Z12").isNull(), lit(0)).otherwise(col("Z12")).alias("Z12"), 
        when(col("Z13").isNull(), lit(0)).otherwise(col("Z13")).alias("Z13"), 
        when(col("Z14").isNull(), lit(0)).otherwise(col("Z14")).alias("Z14"), 
        when(col("Z15").isNull(), lit(0)).otherwise(col("Z15")).alias("Z15"), 
        when(col("Z16").isNull(), lit(0)).otherwise(col("Z16")).alias("Z16"), 
        when(col("Z17").isNull(), lit(0)).otherwise(col("Z17")).alias("Z17"), 
        when(col("Z18").isNull(), lit(0)).otherwise(col("Z18")).alias("Z18"), 
        when(col("Z19").isNull(), lit(0)).otherwise(col("Z19")).alias("Z19"), 
        when(col("Z20").isNull(), lit(0)).otherwise(col("Z20")).alias("Z20"), 
        when(col("Z21").isNull(), lit(0)).otherwise(col("Z21")).alias("Z21"), 
        when(col("Z22").isNull(), lit(0)).otherwise(col("Z22")).alias("Z22"), 
        when(col("Z23").isNull(), lit(0)).otherwise(col("Z23")).alias("Z23"), 
        when(col("Z28").isNull(), lit(0)).otherwise(col("Z28")).alias("Z28"), 
        when(col("Z29").isNull(), lit(0)).otherwise(col("Z29")).alias("Z29"), 
        when(col("Z30").isNull(), lit(0)).otherwise(col("Z30")).alias("Z30"), 
        when(col("Z31").isNull(), lit(0)).otherwise(col("Z31")).alias("Z31"), 
        when(col("Z32").isNull(), lit(0)).otherwise(col("Z32")).alias("Z32"), 
        when(col("Z33").isNull(), lit(0)).otherwise(col("Z33")).alias("Z33"), 
        when(col("Z34").isNull(), lit(0)).otherwise(col("Z34")).alias("Z34"), 
        when(col("Z36").isNull(), lit(0)).otherwise(col("Z36")).alias("Z36"), 
        when(col("Z37").isNull(), lit(0)).otherwise(col("Z37")).alias("Z37"), 
        when(col("Z38").isNull(), lit(0)).otherwise(col("Z38")).alias("Z38"), 
        when(col("Z39").isNull(), lit(0)).otherwise(col("Z39")).alias("Z39"), 
        when(col("E00_Running3").isNull(), lit(0)).otherwise(col("E00_Running3")).alias("E00_Running3"), 
        when(col("E01_Running3").isNull(), lit(0)).otherwise(col("E01_Running3")).alias("E01_Running3"), 
        when(col("E02_Running3").isNull(), lit(0)).otherwise(col("E02_Running3")).alias("E02_Running3"), 
        when(col("E03_Running3").isNull(), lit(0)).otherwise(col("E03_Running3")).alias("E03_Running3"), 
        when(col("E04_Running3").isNull(), lit(0)).otherwise(col("E04_Running3")).alias("E04_Running3"), 
        when(col("E05_Running3").isNull(), lit(0)).otherwise(col("E05_Running3")).alias("E05_Running3"), 
        when(col("E06_Running3").isNull(), lit(0)).otherwise(col("E06_Running3")).alias("E06_Running3"), 
        when(col("E07_Running3").isNull(), lit(0)).otherwise(col("E07_Running3")).alias("E07_Running3"), 
        when(col("E08_Running3").isNull(), lit(0)).otherwise(col("E08_Running3")).alias("E08_Running3"), 
        when(col("E09_Running3").isNull(), lit(0)).otherwise(col("E09_Running3")).alias("E09_Running3"), 
        when(col("E10_Running3").isNull(), lit(0)).otherwise(col("E10_Running3")).alias("E10_Running3"), 
        when(col("E11_Running3").isNull(), lit(0)).otherwise(col("E11_Running3")).alias("E11_Running3"), 
        when(col("E13_Running3").isNull(), lit(0)).otherwise(col("E13_Running3")).alias("E13_Running3"), 
        when(col("E15_Running3").isNull(), lit(0)).otherwise(col("E15_Running3")).alias("E15_Running3"), 
        when(col("E16_Running3").isNull(), lit(0)).otherwise(col("E16_Running3")).alias("E16_Running3"), 
        when(col("E20_Running3").isNull(), lit(0)).otherwise(col("E20_Running3")).alias("E20_Running3"), 
        when(col("E21_Running3").isNull(), lit(0)).otherwise(col("E21_Running3")).alias("E21_Running3"), 
        when(col("E22_Running3").isNull(), lit(0)).otherwise(col("E22_Running3")).alias("E22_Running3"), 
        when(col("E23_Running3").isNull(), lit(0)).otherwise(col("E23_Running3")).alias("E23_Running3"), 
        when(col("E24_Running3").isNull(), lit(0)).otherwise(col("E24_Running3")).alias("E24_Running3"), 
        when(col("E25_Running3").isNull(), lit(0)).otherwise(col("E25_Running3")).alias("E25_Running3"), 
        when(col("E26_Running3").isNull(), lit(0)).otherwise(col("E26_Running3")).alias("E26_Running3"), 
        when(col("E27_Running3").isNull(), lit(0)).otherwise(col("E27_Running3")).alias("E27_Running3"), 
        when(col("E28_Running3").isNull(), lit(0)).otherwise(col("E28_Running3")).alias("E28_Running3"), 
        when(col("E29_Running3").isNull(), lit(0)).otherwise(col("E29_Running3")).alias("E29_Running3"), 
        when(col("E30_Running3").isNull(), lit(0)).otherwise(col("E30_Running3")).alias("E30_Running3"), 
        when(col("E31_Running3").isNull(), lit(0)).otherwise(col("E31_Running3")).alias("E31_Running3"), 
        when(col("E32_Running3").isNull(), lit(0)).otherwise(col("E32_Running3")).alias("E32_Running3"), 
        when(col("E34_Running3").isNull(), lit(0)).otherwise(col("E34_Running3")).alias("E34_Running3"), 
        when(col("E35_Running3").isNull(), lit(0)).otherwise(col("E35_Running3")).alias("E35_Running3"), 
        when(col("E36_Running3").isNull(), lit(0)).otherwise(col("E36_Running3")).alias("E36_Running3"), 
        when(col("E40_Running3").isNull(), lit(0)).otherwise(col("E40_Running3")).alias("E40_Running3"), 
        when(col("E41_Running3").isNull(), lit(0)).otherwise(col("E41_Running3")).alias("E41_Running3"), 
        when(col("E42_Running3").isNull(), lit(0)).otherwise(col("E42_Running3")).alias("E42_Running3"), 
        when(col("E43_Running3").isNull(), lit(0)).otherwise(col("E43_Running3")).alias("E43_Running3"), 
        when(col("E44_Running3").isNull(), lit(0)).otherwise(col("E44_Running3")).alias("E44_Running3"), 
        when(col("E45_Running3").isNull(), lit(0)).otherwise(col("E45_Running3")).alias("E45_Running3"), 
        when(col("E46_Running3").isNull(), lit(0)).otherwise(col("E46_Running3")).alias("E46_Running3"), 
        when(col("E50_Running3").isNull(), lit(0)).otherwise(col("E50_Running3")).alias("E50_Running3"), 
        when(col("E51_Running3").isNull(), lit(0)).otherwise(col("E51_Running3")).alias("E51_Running3"), 
        when(col("E52_Running3").isNull(), lit(0)).otherwise(col("E52_Running3")).alias("E52_Running3"), 
        when(col("E53_Running3").isNull(), lit(0)).otherwise(col("E53_Running3")).alias("E53_Running3"), 
        when(col("E54_Running3").isNull(), lit(0)).otherwise(col("E54_Running3")).alias("E54_Running3"), 
        when(col("E55_Running3").isNull(), lit(0)).otherwise(col("E55_Running3")).alias("E55_Running3"), 
        when(col("E56_Running3").isNull(), lit(0)).otherwise(col("E56_Running3")).alias("E56_Running3"), 
        when(col("E58_Running3").isNull(), lit(0)).otherwise(col("E58_Running3")).alias("E58_Running3"), 
        when(col("E59_Running3").isNull(), lit(0)).otherwise(col("E59_Running3")).alias("E59_Running3"), 
        when(col("E60_Running3").isNull(), lit(0)).otherwise(col("E60_Running3")).alias("E60_Running3"), 
        when(col("E61_Running3").isNull(), lit(0)).otherwise(col("E61_Running3")).alias("E61_Running3"), 
        when(col("E63_Running3").isNull(), lit(0)).otherwise(col("E63_Running3")).alias("E63_Running3"), 
        when(col("E64_Running3").isNull(), lit(0)).otherwise(col("E64_Running3")).alias("E64_Running3"), 
        when(col("E65_Running3").isNull(), lit(0)).otherwise(col("E65_Running3")).alias("E65_Running3"), 
        when(col("E66_Running3").isNull(), lit(0)).otherwise(col("E66_Running3")).alias("E66_Running3"), 
        when(col("E67_Running3").isNull(), lit(0)).otherwise(col("E67_Running3")).alias("E67_Running3"), 
        when(col("E68_Running3").isNull(), lit(0)).otherwise(col("E68_Running3")).alias("E68_Running3"), 
        when(col("E70_Running3").isNull(), lit(0)).otherwise(col("E70_Running3")).alias("E70_Running3"), 
        when(col("E71_Running3").isNull(), lit(0)).otherwise(col("E71_Running3")).alias("E71_Running3"), 
        when(col("E72_Running3").isNull(), lit(0)).otherwise(col("E72_Running3")).alias("E72_Running3"), 
        when(col("E73_Running3").isNull(), lit(0)).otherwise(col("E73_Running3")).alias("E73_Running3"), 
        when(col("E74_Running3").isNull(), lit(0)).otherwise(col("E74_Running3")).alias("E74_Running3"), 
        when(col("E75_Running3").isNull(), lit(0)).otherwise(col("E75_Running3")).alias("E75_Running3"), 
        when(col("E76_Running3").isNull(), lit(0)).otherwise(col("E76_Running3")).alias("E76_Running3"), 
        when(col("E77_Running3").isNull(), lit(0)).otherwise(col("E77_Running3")).alias("E77_Running3"), 
        when(col("E78_Running3").isNull(), lit(0)).otherwise(col("E78_Running3")).alias("E78_Running3"), 
        when(col("E79_Running3").isNull(), lit(0)).otherwise(col("E79_Running3")).alias("E79_Running3"), 
        when(col("E80_Running3").isNull(), lit(0)).otherwise(col("E80_Running3")).alias("E80_Running3"), 
        when(col("E83_Running3").isNull(), lit(0)).otherwise(col("E83_Running3")).alias("E83_Running3"), 
        when(col("E84_Running3").isNull(), lit(0)).otherwise(col("E84_Running3")).alias("E84_Running3"), 
        when(col("E85_Running3").isNull(), lit(0)).otherwise(col("E85_Running3")).alias("E85_Running3"), 
        when(col("E86_Running3").isNull(), lit(0)).otherwise(col("E86_Running3")).alias("E86_Running3"), 
        when(col("E87_Running3").isNull(), lit(0)).otherwise(col("E87_Running3")).alias("E87_Running3"), 
        when(col("E88_Running3").isNull(), lit(0)).otherwise(col("E88_Running3")).alias("E88_Running3"), 
        when(col("E89_Running3").isNull(), lit(0)).otherwise(col("E89_Running3")).alias("E89_Running3"), 
        when(col("F30_Running3").isNull(), lit(0)).otherwise(col("F30_Running3")).alias("F30_Running3"), 
        when(col("F31_Running3").isNull(), lit(0)).otherwise(col("F31_Running3")).alias("F31_Running3"), 
        when(col("F32_Running3").isNull(), lit(0)).otherwise(col("F32_Running3")).alias("F32_Running3"), 
        when(col("F33_Running3").isNull(), lit(0)).otherwise(col("F33_Running3")).alias("F33_Running3"), 
        when(col("F34_Running3").isNull(), lit(0)).otherwise(col("F34_Running3")).alias("F34_Running3"), 
        when(col("F39_Running3").isNull(), lit(0)).otherwise(col("F39_Running3")).alias("F39_Running3"), 
        when(col("M1A_Running3").isNull(), lit(0)).otherwise(col("M1A_Running3")).alias("M1A_Running3"), 
        when(col("M10_Running3").isNull(), lit(0)).otherwise(col("M10_Running3")).alias("M10_Running3"), 
        when(col("M11_Running3").isNull(), lit(0)).otherwise(col("M11_Running3")).alias("M11_Running3"), 
        when(col("M12_Running3").isNull(), lit(0)).otherwise(col("M12_Running3")).alias("M12_Running3"), 
        when(col("M13_Running3").isNull(), lit(0)).otherwise(col("M13_Running3")).alias("M13_Running3"), 
        when(col("M14_Running3").isNull(), lit(0)).otherwise(col("M14_Running3")).alias("M14_Running3"), 
        when(col("M15_Running3").isNull(), lit(0)).otherwise(col("M15_Running3")).alias("M15_Running3"), 
        when(col("M16_Running3").isNull(), lit(0)).otherwise(col("M16_Running3")).alias("M16_Running3"), 
        when(col("M17_Running3").isNull(), lit(0)).otherwise(col("M17_Running3")).alias("M17_Running3"), 
        when(col("M18_Running3").isNull(), lit(0)).otherwise(col("M18_Running3")).alias("M18_Running3"), 
        when(col("M19_Running3").isNull(), lit(0)).otherwise(col("M19_Running3")).alias("M19_Running3"), 
        when(col("M40_Running3").isNull(), lit(0)).otherwise(col("M40_Running3")).alias("M40_Running3"), 
        when(col("M41_Running3").isNull(), lit(0)).otherwise(col("M41_Running3")).alias("M41_Running3"), 
        when(col("M42_Running3").isNull(), lit(0)).otherwise(col("M42_Running3")).alias("M42_Running3"), 
        when(col("M43_Running3").isNull(), lit(0)).otherwise(col("M43_Running3")).alias("M43_Running3"), 
        when(col("M45_Running3").isNull(), lit(0)).otherwise(col("M45_Running3")).alias("M45_Running3"), 
        when(col("M46_Running3").isNull(), lit(0)).otherwise(col("M46_Running3")).alias("M46_Running3"), 
        when(col("M47_Running3").isNull(), lit(0)).otherwise(col("M47_Running3")).alias("M47_Running3"), 
        when(col("M48_Running3").isNull(), lit(0)).otherwise(col("M48_Running3")).alias("M48_Running3"), 
        when(col("M49_Running3").isNull(), lit(0)).otherwise(col("M49_Running3")).alias("M49_Running3"), 
        when(col("O00_Running3").isNull(), lit(0)).otherwise(col("O00_Running3")).alias("O00_Running3"), 
        when(col("O01_Running3").isNull(), lit(0)).otherwise(col("O01_Running3")).alias("O01_Running3"), 
        when(col("O02_Running3").isNull(), lit(0)).otherwise(col("O02_Running3")).alias("O02_Running3"), 
        when(col("O03_Running3").isNull(), lit(0)).otherwise(col("O03_Running3")).alias("O03_Running3"), 
        when(col("O04_Running3").isNull(), lit(0)).otherwise(col("O04_Running3")).alias("O04_Running3"), 
        when(col("O07_Running3").isNull(), lit(0)).otherwise(col("O07_Running3")).alias("O07_Running3"), 
        when(col("O08_Running3").isNull(), lit(0)).otherwise(col("O08_Running3")).alias("O08_Running3"), 
        when(col("O09_Running3").isNull(), lit(0)).otherwise(col("O09_Running3")).alias("O09_Running3"), 
        when(col("O20_Running3").isNull(), lit(0)).otherwise(col("O20_Running3")).alias("O20_Running3"), 
        when(col("O21_Running3").isNull(), lit(0)).otherwise(col("O21_Running3")).alias("O21_Running3"), 
        when(col("O22_Running3").isNull(), lit(0)).otherwise(col("O22_Running3")).alias("O22_Running3"), 
        when(col("O23_Running3").isNull(), lit(0)).otherwise(col("O23_Running3")).alias("O23_Running3"), 
        when(col("O24_Running3").isNull(), lit(0)).otherwise(col("O24_Running3")).alias("O24_Running3"), 
        when(col("O25_Running3").isNull(), lit(0)).otherwise(col("O25_Running3")).alias("O25_Running3"), 
        when(col("O26_Running3").isNull(), lit(0)).otherwise(col("O26_Running3")).alias("O26_Running3"), 
        when(col("O28_Running3").isNull(), lit(0)).otherwise(col("O28_Running3")).alias("O28_Running3"), 
        when(col("O29_Running3").isNull(), lit(0)).otherwise(col("O29_Running3")).alias("O29_Running3"), 
        when(col("O30_Running3").isNull(), lit(0)).otherwise(col("O30_Running3")).alias("O30_Running3"), 
        when(col("O31_Running3").isNull(), lit(0)).otherwise(col("O31_Running3")).alias("O31_Running3"), 
        when(col("O32_Running3").isNull(), lit(0)).otherwise(col("O32_Running3")).alias("O32_Running3"), 
        when(col("O33_Running3").isNull(), lit(0)).otherwise(col("O33_Running3")).alias("O33_Running3"), 
        when(col("O34_Running3").isNull(), lit(0)).otherwise(col("O34_Running3")).alias("O34_Running3"), 
        when(col("O35_Running3").isNull(), lit(0)).otherwise(col("O35_Running3")).alias("O35_Running3"), 
        when(col("O36_Running3").isNull(), lit(0)).otherwise(col("O36_Running3")).alias("O36_Running3"), 
        when(col("R10_Running3").isNull(), lit(0)).otherwise(col("R10_Running3")).alias("R10_Running3"), 
        when(col("R11_Running3").isNull(), lit(0)).otherwise(col("R11_Running3")).alias("R11_Running3"), 
        when(col("R12_Running3").isNull(), lit(0)).otherwise(col("R12_Running3")).alias("R12_Running3"), 
        when(col("R13_Running3").isNull(), lit(0)).otherwise(col("R13_Running3")).alias("R13_Running3"), 
        when(col("R14_Running3").isNull(), lit(0)).otherwise(col("R14_Running3")).alias("R14_Running3"), 
        when(col("R15_Running3").isNull(), lit(0)).otherwise(col("R15_Running3")).alias("R15_Running3"), 
        when(col("R16_Running3").isNull(), lit(0)).otherwise(col("R16_Running3")).alias("R16_Running3"), 
        when(col("R17_Running3").isNull(), lit(0)).otherwise(col("R17_Running3")).alias("R17_Running3"), 
        when(col("R18_Running3").isNull(), lit(0)).otherwise(col("R18_Running3")).alias("R18_Running3"), 
        when(col("R19_Running3").isNull(), lit(0)).otherwise(col("R19_Running3")).alias("R19_Running3"), 
        when(col("Z00_Running3").isNull(), lit(0)).otherwise(col("Z00_Running3")).alias("Z00_Running3"), 
        when(col("Z01_Running3").isNull(), lit(0)).otherwise(col("Z01_Running3")).alias("Z01_Running3"), 
        when(col("Z02_Running3").isNull(), lit(0)).otherwise(col("Z02_Running3")).alias("Z02_Running3"), 
        when(col("Z3A_Running3").isNull(), lit(0)).otherwise(col("Z3A_Running3")).alias("Z3A_Running3"), 
        when(col("Z03_Running3").isNull(), lit(0)).otherwise(col("Z03_Running3")).alias("Z03_Running3"), 
        when(col("Z04_Running3").isNull(), lit(0)).otherwise(col("Z04_Running3")).alias("Z04_Running3"), 
        when(col("Z05_Running3").isNull(), lit(0)).otherwise(col("Z05_Running3")).alias("Z05_Running3"), 
        when(col("Z08_Running3").isNull(), lit(0)).otherwise(col("Z08_Running3")).alias("Z08_Running3"), 
        when(col("Z09_Running3").isNull(), lit(0)).otherwise(col("Z09_Running3")).alias("Z09_Running3"), 
        when(col("Z11_Running3").isNull(), lit(0)).otherwise(col("Z11_Running3")).alias("Z11_Running3"), 
        when(col("Z12_Running3").isNull(), lit(0)).otherwise(col("Z12_Running3")).alias("Z12_Running3"), 
        when(col("Z13_Running3").isNull(), lit(0)).otherwise(col("Z13_Running3")).alias("Z13_Running3"), 
        when(col("Z14_Running3").isNull(), lit(0)).otherwise(col("Z14_Running3")).alias("Z14_Running3"), 
        when(col("Z15_Running3").isNull(), lit(0)).otherwise(col("Z15_Running3")).alias("Z15_Running3"), 
        when(col("Z16_Running3").isNull(), lit(0)).otherwise(col("Z16_Running3")).alias("Z16_Running3"), 
        when(col("Z17_Running3").isNull(), lit(0)).otherwise(col("Z17_Running3")).alias("Z17_Running3"), 
        when(col("Z18_Running3").isNull(), lit(0)).otherwise(col("Z18_Running3")).alias("Z18_Running3"), 
        when(col("Z19_Running3").isNull(), lit(0)).otherwise(col("Z19_Running3")).alias("Z19_Running3"), 
        when(col("Z20_Running3").isNull(), lit(0)).otherwise(col("Z20_Running3")).alias("Z20_Running3"), 
        when(col("Z21_Running3").isNull(), lit(0)).otherwise(col("Z21_Running3")).alias("Z21_Running3"), 
        when(col("Z22_Running3").isNull(), lit(0)).otherwise(col("Z22_Running3")).alias("Z22_Running3"), 
        when(col("Z23_Running3").isNull(), lit(0)).otherwise(col("Z23_Running3")).alias("Z23_Running3"), 
        when(col("Z28_Running3").isNull(), lit(0)).otherwise(col("Z28_Running3")).alias("Z28_Running3"), 
        when(col("Z29_Running3").isNull(), lit(0)).otherwise(col("Z29_Running3")).alias("Z29_Running3"), 
        when(col("Z30_Running3").isNull(), lit(0)).otherwise(col("Z30_Running3")).alias("Z30_Running3"), 
        when(col("Z31_Running3").isNull(), lit(0)).otherwise(col("Z31_Running3")).alias("Z31_Running3"), 
        when(col("Z32_Running3").isNull(), lit(0)).otherwise(col("Z32_Running3")).alias("Z32_Running3"), 
        when(col("Z33_Running3").isNull(), lit(0)).otherwise(col("Z33_Running3")).alias("Z33_Running3"), 
        when(col("Z34_Running3").isNull(), lit(0)).otherwise(col("Z34_Running3")).alias("Z34_Running3"), 
        when(col("Z36_Running3").isNull(), lit(0)).otherwise(col("Z36_Running3")).alias("Z36_Running3"), 
        when(col("Z37_Running3").isNull(), lit(0)).otherwise(col("Z37_Running3")).alias("Z37_Running3"), 
        when(col("Z38_Running3").isNull(), lit(0)).otherwise(col("Z38_Running3")).alias("Z38_Running3"), 
        when(col("Z39_Running3").isNull(), lit(0)).otherwise(col("Z39_Running3")).alias("Z39_Running3"), 
        when(col("E00_Running6").isNull(), lit(0)).otherwise(col("E00_Running6")).alias("E00_Running6"), 
        when(col("E01_Running6").isNull(), lit(0)).otherwise(col("E01_Running6")).alias("E01_Running6"), 
        when(col("E02_Running6").isNull(), lit(0)).otherwise(col("E02_Running6")).alias("E02_Running6"), 
        when(col("E03_Running6").isNull(), lit(0)).otherwise(col("E03_Running6")).alias("E03_Running6"), 
        when(col("E04_Running6").isNull(), lit(0)).otherwise(col("E04_Running6")).alias("E04_Running6"), 
        when(col("E05_Running6").isNull(), lit(0)).otherwise(col("E05_Running6")).alias("E05_Running6"), 
        when(col("E06_Running6").isNull(), lit(0)).otherwise(col("E06_Running6")).alias("E06_Running6"), 
        when(col("E07_Running6").isNull(), lit(0)).otherwise(col("E07_Running6")).alias("E07_Running6"), 
        when(col("E08_Running6").isNull(), lit(0)).otherwise(col("E08_Running6")).alias("E08_Running6"), 
        when(col("E09_Running6").isNull(), lit(0)).otherwise(col("E09_Running6")).alias("E09_Running6"), 
        when(col("E10_Running6").isNull(), lit(0)).otherwise(col("E10_Running6")).alias("E10_Running6"), 
        when(col("E11_Running6").isNull(), lit(0)).otherwise(col("E11_Running6")).alias("E11_Running6"), 
        when(col("E13_Running6").isNull(), lit(0)).otherwise(col("E13_Running6")).alias("E13_Running6"), 
        when(col("E15_Running6").isNull(), lit(0)).otherwise(col("E15_Running6")).alias("E15_Running6"), 
        when(col("E16_Running6").isNull(), lit(0)).otherwise(col("E16_Running6")).alias("E16_Running6"), 
        when(col("E20_Running6").isNull(), lit(0)).otherwise(col("E20_Running6")).alias("E20_Running6"), 
        when(col("E21_Running6").isNull(), lit(0)).otherwise(col("E21_Running6")).alias("E21_Running6"), 
        when(col("E22_Running6").isNull(), lit(0)).otherwise(col("E22_Running6")).alias("E22_Running6"), 
        when(col("E23_Running6").isNull(), lit(0)).otherwise(col("E23_Running6")).alias("E23_Running6"), 
        when(col("E24_Running6").isNull(), lit(0)).otherwise(col("E24_Running6")).alias("E24_Running6"), 
        when(col("E25_Running6").isNull(), lit(0)).otherwise(col("E25_Running6")).alias("E25_Running6"), 
        when(col("E26_Running6").isNull(), lit(0)).otherwise(col("E26_Running6")).alias("E26_Running6"), 
        when(col("E27_Running6").isNull(), lit(0)).otherwise(col("E27_Running6")).alias("E27_Running6"), 
        when(col("E28_Running6").isNull(), lit(0)).otherwise(col("E28_Running6")).alias("E28_Running6"), 
        when(col("E29_Running6").isNull(), lit(0)).otherwise(col("E29_Running6")).alias("E29_Running6"), 
        when(col("E30_Running6").isNull(), lit(0)).otherwise(col("E30_Running6")).alias("E30_Running6"), 
        when(col("E31_Running6").isNull(), lit(0)).otherwise(col("E31_Running6")).alias("E31_Running6"), 
        when(col("E32_Running6").isNull(), lit(0)).otherwise(col("E32_Running6")).alias("E32_Running6"), 
        when(col("E34_Running6").isNull(), lit(0)).otherwise(col("E34_Running6")).alias("E34_Running6"), 
        when(col("E35_Running6").isNull(), lit(0)).otherwise(col("E35_Running6")).alias("E35_Running6"), 
        when(col("E36_Running6").isNull(), lit(0)).otherwise(col("E36_Running6")).alias("E36_Running6"), 
        when(col("E40_Running6").isNull(), lit(0)).otherwise(col("E40_Running6")).alias("E40_Running6"), 
        when(col("E41_Running6").isNull(), lit(0)).otherwise(col("E41_Running6")).alias("E41_Running6"), 
        when(col("E42_Running6").isNull(), lit(0)).otherwise(col("E42_Running6")).alias("E42_Running6"), 
        when(col("E43_Running6").isNull(), lit(0)).otherwise(col("E43_Running6")).alias("E43_Running6"), 
        when(col("E44_Running6").isNull(), lit(0)).otherwise(col("E44_Running6")).alias("E44_Running6"), 
        when(col("E45_Running6").isNull(), lit(0)).otherwise(col("E45_Running6")).alias("E45_Running6"), 
        when(col("E46_Running6").isNull(), lit(0)).otherwise(col("E46_Running6")).alias("E46_Running6"), 
        when(col("E50_Running6").isNull(), lit(0)).otherwise(col("E50_Running6")).alias("E50_Running6"), 
        when(col("E51_Running6").isNull(), lit(0)).otherwise(col("E51_Running6")).alias("E51_Running6"), 
        when(col("E52_Running6").isNull(), lit(0)).otherwise(col("E52_Running6")).alias("E52_Running6"), 
        when(col("E53_Running6").isNull(), lit(0)).otherwise(col("E53_Running6")).alias("E53_Running6"), 
        when(col("E54_Running6").isNull(), lit(0)).otherwise(col("E54_Running6")).alias("E54_Running6"), 
        when(col("E55_Running6").isNull(), lit(0)).otherwise(col("E55_Running6")).alias("E55_Running6"), 
        when(col("E56_Running6").isNull(), lit(0)).otherwise(col("E56_Running6")).alias("E56_Running6"), 
        when(col("E58_Running6").isNull(), lit(0)).otherwise(col("E58_Running6")).alias("E58_Running6"), 
        when(col("E59_Running6").isNull(), lit(0)).otherwise(col("E59_Running6")).alias("E59_Running6"), 
        when(col("E60_Running6").isNull(), lit(0)).otherwise(col("E60_Running6")).alias("E60_Running6"), 
        when(col("E61_Running6").isNull(), lit(0)).otherwise(col("E61_Running6")).alias("E61_Running6"), 
        when(col("E63_Running6").isNull(), lit(0)).otherwise(col("E63_Running6")).alias("E63_Running6"), 
        when(col("E64_Running6").isNull(), lit(0)).otherwise(col("E64_Running6")).alias("E64_Running6"), 
        when(col("E65_Running6").isNull(), lit(0)).otherwise(col("E65_Running6")).alias("E65_Running6"), 
        when(col("E66_Running6").isNull(), lit(0)).otherwise(col("E66_Running6")).alias("E66_Running6"), 
        when(col("E67_Running6").isNull(), lit(0)).otherwise(col("E67_Running6")).alias("E67_Running6"), 
        when(col("E70_Running6").isNull(), lit(0)).otherwise(col("E70_Running6")).alias("E70_Running6"), 
        when(col("E71_Running6").isNull(), lit(0)).otherwise(col("E71_Running6")).alias("E71_Running6"), 
        when(col("E72_Running6").isNull(), lit(0)).otherwise(col("E72_Running6")).alias("E72_Running6"), 
        when(col("E73_Running6").isNull(), lit(0)).otherwise(col("E73_Running6")).alias("E73_Running6"), 
        when(col("E74_Running6").isNull(), lit(0)).otherwise(col("E74_Running6")).alias("E74_Running6"), 
        when(col("E75_Running6").isNull(), lit(0)).otherwise(col("E75_Running6")).alias("E75_Running6"), 
        when(col("E76_Running6").isNull(), lit(0)).otherwise(col("E76_Running6")).alias("E76_Running6"), 
        when(col("E77_Running6").isNull(), lit(0)).otherwise(col("E77_Running6")).alias("E77_Running6"), 
        when(col("E78_Running6").isNull(), lit(0)).otherwise(col("E78_Running6")).alias("E78_Running6"), 
        when(col("E79_Running6").isNull(), lit(0)).otherwise(col("E79_Running6")).alias("E79_Running6"), 
        when(col("E80_Running6").isNull(), lit(0)).otherwise(col("E80_Running6")).alias("E80_Running6"), 
        when(col("E83_Running6").isNull(), lit(0)).otherwise(col("E83_Running6")).alias("E83_Running6"), 
        when(col("E84_Running6").isNull(), lit(0)).otherwise(col("E84_Running6")).alias("E84_Running6"), 
        when(col("E85_Running6").isNull(), lit(0)).otherwise(col("E85_Running6")).alias("E85_Running6"), 
        when(col("E86_Running6").isNull(), lit(0)).otherwise(col("E86_Running6")).alias("E86_Running6"), 
        when(col("E87_Running6").isNull(), lit(0)).otherwise(col("E87_Running6")).alias("E87_Running6"), 
        when(col("E88_Running6").isNull(), lit(0)).otherwise(col("E88_Running6")).alias("E88_Running6"), 
        when(col("E89_Running6").isNull(), lit(0)).otherwise(col("E89_Running6")).alias("E89_Running6"), 
        when(col("D6_Running6").isNull(), lit(0)).otherwise(col("D6_Running6")).alias("D6_Running6"), 
        when(col("E0_Running6").isNull(), lit(0)).otherwise(col("E0_Running6")).alias("E0_Running6"), 
        when(col("E1_Running6").isNull(), lit(0)).otherwise(col("E1_Running6")).alias("E1_Running6"), 
        when(col("E7_Running6").isNull(), lit(0)).otherwise(col("E7_Running6")).alias("E7_Running6"), 
        when(col("I1_Running6").isNull(), lit(0)).otherwise(col("I1_Running6")).alias("I1_Running6"), 
        when(col("I2_Running6").isNull(), lit(0)).otherwise(col("I2_Running6")).alias("I2_Running6"), 
        when(col("I5_Running6").isNull(), lit(0)).otherwise(col("I5_Running6")).alias("I5_Running6"), 
        when(col("N1_Running6").isNull(), lit(0)).otherwise(col("N1_Running6")).alias("N1_Running6"), 
        when(col("A0_Running6").isNull(), lit(0)).otherwise(col("A0_Running6")).alias("A0_Running6"), 
        when(col("A1_Running6").isNull(), lit(0)).otherwise(col("A1_Running6")).alias("A1_Running6"), 
        when(col("A2_Running6").isNull(), lit(0)).otherwise(col("A2_Running6")).alias("A2_Running6"), 
        when(col("A3_Running6").isNull(), lit(0)).otherwise(col("A3_Running6")).alias("A3_Running6"), 
        when(col("A4_Running6").isNull(), lit(0)).otherwise(col("A4_Running6")).alias("A4_Running6"), 
        when(col("A5_Running6").isNull(), lit(0)).otherwise(col("A5_Running6")).alias("A5_Running6"), 
        when(col("A6_Running6").isNull(), lit(0)).otherwise(col("A6_Running6")).alias("A6_Running6"), 
        when(col("A7_Running6").isNull(), lit(0)).otherwise(col("A7_Running6")).alias("A7_Running6"), 
        when(col("A8_Running6").isNull(), lit(0)).otherwise(col("A8_Running6")).alias("A8_Running6"), 
        when(col("A9_Running6").isNull(), lit(0)).otherwise(col("A9_Running6")).alias("A9_Running6"), 
        when(col("B0_Running6").isNull(), lit(0)).otherwise(col("B0_Running6")).alias("B0_Running6"), 
        when(col("B1_Running6").isNull(), lit(0)).otherwise(col("B1_Running6")).alias("B1_Running6"), 
        when(col("B2_Running6").isNull(), lit(0)).otherwise(col("B2_Running6")).alias("B2_Running6"), 
        when(col("B3_Running6").isNull(), lit(0)).otherwise(col("B3_Running6")).alias("B3_Running6"), 
        when(col("B4_Running6").isNull(), lit(0)).otherwise(col("B4_Running6")).alias("B4_Running6"), 
        when(col("B5_Running6").isNull(), lit(0)).otherwise(col("B5_Running6")).alias("B5_Running6"), 
        when(col("B6_Running6").isNull(), lit(0)).otherwise(col("B6_Running6")).alias("B6_Running6"), 
        when(col("B7_Running6").isNull(), lit(0)).otherwise(col("B7_Running6")).alias("B7_Running6"), 
        when(col("B8_Running6").isNull(), lit(0)).otherwise(col("B8_Running6")).alias("B8_Running6"), 
        when(col("B9_Running6").isNull(), lit(0)).otherwise(col("B9_Running6")).alias("B9_Running6"), 
        when(col("C0_Running6").isNull(), lit(0)).otherwise(col("C0_Running6")).alias("C0_Running6"), 
        when(col("C1_Running6").isNull(), lit(0)).otherwise(col("C1_Running6")).alias("C1_Running6"), 
        when(col("C2_Running6").isNull(), lit(0)).otherwise(col("C2_Running6")).alias("C2_Running6"), 
        when(col("C3_Running6").isNull(), lit(0)).otherwise(col("C3_Running6")).alias("C3_Running6"), 
        when(col("C4_Running6").isNull(), lit(0)).otherwise(col("C4_Running6")).alias("C4_Running6"), 
        when(col("C5_Running6").isNull(), lit(0)).otherwise(col("C5_Running6")).alias("C5_Running6"), 
        when(col("C6_Running6").isNull(), lit(0)).otherwise(col("C6_Running6")).alias("C6_Running6"), 
        when(col("C7_Running6").isNull(), lit(0)).otherwise(col("C7_Running6")).alias("C7_Running6"), 
        when(col("C8_Running6").isNull(), lit(0)).otherwise(col("C8_Running6")).alias("C8_Running6"), 
        when(col("C9_Running6").isNull(), lit(0)).otherwise(col("C9_Running6")).alias("C9_Running6"), 
        when(col("D0_Running6").isNull(), lit(0)).otherwise(col("D0_Running6")).alias("D0_Running6"), 
        when(col("D1_Running6").isNull(), lit(0)).otherwise(col("D1_Running6")).alias("D1_Running6"), 
        when(col("D2_Running6").isNull(), lit(0)).otherwise(col("D2_Running6")).alias("D2_Running6"), 
        when(col("D3_Running6").isNull(), lit(0)).otherwise(col("D3_Running6")).alias("D3_Running6"), 
        when(col("D4_Running6").isNull(), lit(0)).otherwise(col("D4_Running6")).alias("D4_Running6"), 
        when(col("D5_Running6").isNull(), lit(0)).otherwise(col("D5_Running6")).alias("D5_Running6"), 
        when(col("D7_Running6").isNull(), lit(0)).otherwise(col("D7_Running6")).alias("D7_Running6"), 
        when(col("D8_Running6").isNull(), lit(0)).otherwise(col("D8_Running6")).alias("D8_Running6"), 
        when(col("E2_Running6").isNull(), lit(0)).otherwise(col("E2_Running6")).alias("E2_Running6"), 
        when(col("E3_Running6").isNull(), lit(0)).otherwise(col("E3_Running6")).alias("E3_Running6"), 
        when(col("E4_Running6").isNull(), lit(0)).otherwise(col("E4_Running6")).alias("E4_Running6"), 
        when(col("E5_Running6").isNull(), lit(0)).otherwise(col("E5_Running6")).alias("E5_Running6"), 
        when(col("E6_Running6").isNull(), lit(0)).otherwise(col("E6_Running6")).alias("E6_Running6"), 
        when(col("E8_Running6").isNull(), lit(0)).otherwise(col("E8_Running6")).alias("E8_Running6"), 
        when(col("F0_Running6").isNull(), lit(0)).otherwise(col("F0_Running6")).alias("F0_Running6"), 
        when(col("F1_Running6").isNull(), lit(0)).otherwise(col("F1_Running6")).alias("F1_Running6"), 
        when(col("F2_Running6").isNull(), lit(0)).otherwise(col("F2_Running6")).alias("F2_Running6"), 
        when(col("F3_Running6").isNull(), lit(0)).otherwise(col("F3_Running6")).alias("F3_Running6"), 
        when(col("F4_Running6").isNull(), lit(0)).otherwise(col("F4_Running6")).alias("F4_Running6"), 
        when(col("F5_Running6").isNull(), lit(0)).otherwise(col("F5_Running6")).alias("F5_Running6"), 
        when(col("F6_Running6").isNull(), lit(0)).otherwise(col("F6_Running6")).alias("F6_Running6"), 
        when(col("F7_Running6").isNull(), lit(0)).otherwise(col("F7_Running6")).alias("F7_Running6"), 
        when(col("F8_Running6").isNull(), lit(0)).otherwise(col("F8_Running6")).alias("F8_Running6"), 
        when(col("F9_Running6").isNull(), lit(0)).otherwise(col("F9_Running6")).alias("F9_Running6"), 
        when(col("G0_Running6").isNull(), lit(0)).otherwise(col("G0_Running6")).alias("G0_Running6"), 
        when(col("G1_Running6").isNull(), lit(0)).otherwise(col("G1_Running6")).alias("G1_Running6"), 
        when(col("G2_Running6").isNull(), lit(0)).otherwise(col("G2_Running6")).alias("G2_Running6"), 
        when(col("G3_Running6").isNull(), lit(0)).otherwise(col("G3_Running6")).alias("G3_Running6"), 
        when(col("G4_Running6").isNull(), lit(0)).otherwise(col("G4_Running6")).alias("G4_Running6"), 
        when(col("G5_Running6").isNull(), lit(0)).otherwise(col("G5_Running6")).alias("G5_Running6"), 
        when(col("G6_Running6").isNull(), lit(0)).otherwise(col("G6_Running6")).alias("G6_Running6"), 
        when(col("G7_Running6").isNull(), lit(0)).otherwise(col("G7_Running6")).alias("G7_Running6"), 
        when(col("G8_Running6").isNull(), lit(0)).otherwise(col("G8_Running6")).alias("G8_Running6"), 
        when(col("G9_Running6").isNull(), lit(0)).otherwise(col("G9_Running6")).alias("G9_Running6"), 
        when(col("H0_Running6").isNull(), lit(0)).otherwise(col("H0_Running6")).alias("H0_Running6"), 
        when(col("H1_Running6").isNull(), lit(0)).otherwise(col("H1_Running6")).alias("H1_Running6"), 
        when(col("H2_Running6").isNull(), lit(0)).otherwise(col("H2_Running6")).alias("H2_Running6"), 
        when(col("H3_Running6").isNull(), lit(0)).otherwise(col("H3_Running6")).alias("H3_Running6"), 
        when(col("H4_Running6").isNull(), lit(0)).otherwise(col("H4_Running6")).alias("H4_Running6"), 
        when(col("H5_Running6").isNull(), lit(0)).otherwise(col("H5_Running6")).alias("H5_Running6"), 
        when(col("H6_Running6").isNull(), lit(0)).otherwise(col("H6_Running6")).alias("H6_Running6"), 
        when(col("H7_Running6").isNull(), lit(0)).otherwise(col("H7_Running6")).alias("H7_Running6"), 
        when(col("H8_Running6").isNull(), lit(0)).otherwise(col("H8_Running6")).alias("H8_Running6"), 
        when(col("H9_Running6").isNull(), lit(0)).otherwise(col("H9_Running6")).alias("H9_Running6"), 
        when(col("I0_Running6").isNull(), lit(0)).otherwise(col("I0_Running6")).alias("I0_Running6"), 
        when(col("I3_Running6").isNull(), lit(0)).otherwise(col("I3_Running6")).alias("I3_Running6"), 
        when(col("I4_Running6").isNull(), lit(0)).otherwise(col("I4_Running6")).alias("I4_Running6"), 
        when(col("I6_Running6").isNull(), lit(0)).otherwise(col("I6_Running6")).alias("I6_Running6"), 
        when(col("I7_Running6").isNull(), lit(0)).otherwise(col("I7_Running6")).alias("I7_Running6"), 
        when(col("I8_Running6").isNull(), lit(0)).otherwise(col("I8_Running6")).alias("I8_Running6"), 
        when(col("I9_Running6").isNull(), lit(0)).otherwise(col("I9_Running6")).alias("I9_Running6"), 
        when(col("J0_Running6").isNull(), lit(0)).otherwise(col("J0_Running6")).alias("J0_Running6"), 
        when(col("J1_Running6").isNull(), lit(0)).otherwise(col("J1_Running6")).alias("J1_Running6"), 
        when(col("J2_Running6").isNull(), lit(0)).otherwise(col("J2_Running6")).alias("J2_Running6"), 
        when(col("J3_Running6").isNull(), lit(0)).otherwise(col("J3_Running6")).alias("J3_Running6"), 
        when(col("J4_Running6").isNull(), lit(0)).otherwise(col("J4_Running6")).alias("J4_Running6"), 
        when(col("J6_Running6").isNull(), lit(0)).otherwise(col("J6_Running6")).alias("J6_Running6"), 
        when(col("J7_Running6").isNull(), lit(0)).otherwise(col("J7_Running6")).alias("J7_Running6"), 
        when(col("J8_Running6").isNull(), lit(0)).otherwise(col("J8_Running6")).alias("J8_Running6"), 
        when(col("J9_Running6").isNull(), lit(0)).otherwise(col("J9_Running6")).alias("J9_Running6"), 
        when(col("K0_Running6").isNull(), lit(0)).otherwise(col("K0_Running6")).alias("K0_Running6"), 
        when(col("K1_Running6").isNull(), lit(0)).otherwise(col("K1_Running6")).alias("K1_Running6"), 
        when(col("K2_Running6").isNull(), lit(0)).otherwise(col("K2_Running6")).alias("K2_Running6"), 
        when(col("K3_Running6").isNull(), lit(0)).otherwise(col("K3_Running6")).alias("K3_Running6"), 
        when(col("K4_Running6").isNull(), lit(0)).otherwise(col("K4_Running6")).alias("K4_Running6"), 
        when(col("K5_Running6").isNull(), lit(0)).otherwise(col("K5_Running6")).alias("K5_Running6"), 
        when(col("K6_Running6").isNull(), lit(0)).otherwise(col("K6_Running6")).alias("K6_Running6"), 
        when(col("K7_Running6").isNull(), lit(0)).otherwise(col("K7_Running6")).alias("K7_Running6"), 
        when(col("K8_Running6").isNull(), lit(0)).otherwise(col("K8_Running6")).alias("K8_Running6"), 
        when(col("K9_Running6").isNull(), lit(0)).otherwise(col("K9_Running6")).alias("K9_Running6"), 
        when(col("L0_Running6").isNull(), lit(0)).otherwise(col("L0_Running6")).alias("L0_Running6"), 
        when(col("L1_Running6").isNull(), lit(0)).otherwise(col("L1_Running6")).alias("L1_Running6"), 
        when(col("L2_Running6").isNull(), lit(0)).otherwise(col("L2_Running6")).alias("L2_Running6"), 
        when(col("L3_Running6").isNull(), lit(0)).otherwise(col("L3_Running6")).alias("L3_Running6"), 
        when(col("L4_Running6").isNull(), lit(0)).otherwise(col("L4_Running6")).alias("L4_Running6"), 
        when(col("L5_Running6").isNull(), lit(0)).otherwise(col("L5_Running6")).alias("L5_Running6"), 
        when(col("L6_Running6").isNull(), lit(0)).otherwise(col("L6_Running6")).alias("L6_Running6"), 
        when(col("L7_Running6").isNull(), lit(0)).otherwise(col("L7_Running6")).alias("L7_Running6"), 
        when(col("L8_Running6").isNull(), lit(0)).otherwise(col("L8_Running6")).alias("L8_Running6"), 
        when(col("L9_Running6").isNull(), lit(0)).otherwise(col("L9_Running6")).alias("L9_Running6"), 
        when(col("M0_Running6").isNull(), lit(0)).otherwise(col("M0_Running6")).alias("M0_Running6"), 
        when(col("M1_Running6").isNull(), lit(0)).otherwise(col("M1_Running6")).alias("M1_Running6"), 
        when(col("M2_Running6").isNull(), lit(0)).otherwise(col("M2_Running6")).alias("M2_Running6"), 
        when(col("M3_Running6").isNull(), lit(0)).otherwise(col("M3_Running6")).alias("M3_Running6"), 
        when(col("M4_Running6").isNull(), lit(0)).otherwise(col("M4_Running6")).alias("M4_Running6"), 
        when(col("M5_Running6").isNull(), lit(0)).otherwise(col("M5_Running6")).alias("M5_Running6"), 
        when(col("M6_Running6").isNull(), lit(0)).otherwise(col("M6_Running6")).alias("M6_Running6"), 
        when(col("M7_Running6").isNull(), lit(0)).otherwise(col("M7_Running6")).alias("M7_Running6"), 
        when(col("M8_Running6").isNull(), lit(0)).otherwise(col("M8_Running6")).alias("M8_Running6"), 
        when(col("M9_Running6").isNull(), lit(0)).otherwise(col("M9_Running6")).alias("M9_Running6"), 
        when(col("N0_Running6").isNull(), lit(0)).otherwise(col("N0_Running6")).alias("N0_Running6"), 
        when(col("N2_Running6").isNull(), lit(0)).otherwise(col("N2_Running6")).alias("N2_Running6"), 
        when(col("N3_Running6").isNull(), lit(0)).otherwise(col("N3_Running6")).alias("N3_Running6"), 
        when(col("N4_Running6").isNull(), lit(0)).otherwise(col("N4_Running6")).alias("N4_Running6"), 
        when(col("N5_Running6").isNull(), lit(0)).otherwise(col("N5_Running6")).alias("N5_Running6"), 
        when(col("N6_Running6").isNull(), lit(0)).otherwise(col("N6_Running6")).alias("N6_Running6"), 
        when(col("N7_Running6").isNull(), lit(0)).otherwise(col("N7_Running6")).alias("N7_Running6"), 
        when(col("N8_Running6").isNull(), lit(0)).otherwise(col("N8_Running6")).alias("N8_Running6"), 
        when(col("N9_Running6").isNull(), lit(0)).otherwise(col("N9_Running6")).alias("N9_Running6"), 
        when(col("O0_Running6").isNull(), lit(0)).otherwise(col("O0_Running6")).alias("O0_Running6"), 
        when(col("O1_Running6").isNull(), lit(0)).otherwise(col("O1_Running6")).alias("O1_Running6"), 
        when(col("O2_Running6").isNull(), lit(0)).otherwise(col("O2_Running6")).alias("O2_Running6"), 
        when(col("O3_Running6").isNull(), lit(0)).otherwise(col("O3_Running6")).alias("O3_Running6"), 
        when(col("O4_Running6").isNull(), lit(0)).otherwise(col("O4_Running6")).alias("O4_Running6"), 
        when(col("O6_Running6").isNull(), lit(0)).otherwise(col("O6_Running6")).alias("O6_Running6"), 
        when(col("O7_Running6").isNull(), lit(0)).otherwise(col("O7_Running6")).alias("O7_Running6"), 
        when(col("O8_Running6").isNull(), lit(0)).otherwise(col("O8_Running6")).alias("O8_Running6"), 
        when(col("O9_Running6").isNull(), lit(0)).otherwise(col("O9_Running6")).alias("O9_Running6"), 
        when(col("P0_Running6").isNull(), lit(0)).otherwise(col("P0_Running6")).alias("P0_Running6"), 
        when(col("P1_Running6").isNull(), lit(0)).otherwise(col("P1_Running6")).alias("P1_Running6"), 
        when(col("P2_Running6").isNull(), lit(0)).otherwise(col("P2_Running6")).alias("P2_Running6"), 
        when(col("P3_Running6").isNull(), lit(0)).otherwise(col("P3_Running6")).alias("P3_Running6"), 
        when(col("P5_Running6").isNull(), lit(0)).otherwise(col("P5_Running6")).alias("P5_Running6"), 
        when(col("P6_Running6").isNull(), lit(0)).otherwise(col("P6_Running6")).alias("P6_Running6"), 
        when(col("P7_Running6").isNull(), lit(0)).otherwise(col("P7_Running6")).alias("P7_Running6"), 
        when(col("P8_Running6").isNull(), lit(0)).otherwise(col("P8_Running6")).alias("P8_Running6"), 
        when(col("P9_Running6").isNull(), lit(0)).otherwise(col("P9_Running6")).alias("P9_Running6"), 
        when(col("Q0_Running6").isNull(), lit(0)).otherwise(col("Q0_Running6")).alias("Q0_Running6"), 
        when(col("Q1_Running6").isNull(), lit(0)).otherwise(col("Q1_Running6")).alias("Q1_Running6"), 
        when(col("Q2_Running6").isNull(), lit(0)).otherwise(col("Q2_Running6")).alias("Q2_Running6"), 
        when(col("Q3_Running6").isNull(), lit(0)).otherwise(col("Q3_Running6")).alias("Q3_Running6"), 
        when(col("Q4_Running6").isNull(), lit(0)).otherwise(col("Q4_Running6")).alias("Q4_Running6"), 
        when(col("Q5_Running6").isNull(), lit(0)).otherwise(col("Q5_Running6")).alias("Q5_Running6"), 
        when(col("Q6_Running6").isNull(), lit(0)).otherwise(col("Q6_Running6")).alias("Q6_Running6"), 
        when(col("Q7_Running6").isNull(), lit(0)).otherwise(col("Q7_Running6")).alias("Q7_Running6"), 
        when(col("Q8_Running6").isNull(), lit(0)).otherwise(col("Q8_Running6")).alias("Q8_Running6"), 
        when(col("Q9_Running6").isNull(), lit(0)).otherwise(col("Q9_Running6")).alias("Q9_Running6"), 
        when(col("R0_Running6").isNull(), lit(0)).otherwise(col("R0_Running6")).alias("R0_Running6"), 
        when(col("R1_Running6").isNull(), lit(0)).otherwise(col("R1_Running6")).alias("R1_Running6"), 
        when(col("R2_Running6").isNull(), lit(0)).otherwise(col("R2_Running6")).alias("R2_Running6"), 
        when(col("R3_Running6").isNull(), lit(0)).otherwise(col("R3_Running6")).alias("R3_Running6"), 
        when(col("R4_Running6").isNull(), lit(0)).otherwise(col("R4_Running6")).alias("R4_Running6"), 
        when(col("R5_Running6").isNull(), lit(0)).otherwise(col("R5_Running6")).alias("R5_Running6"), 
        when(col("R6_Running6").isNull(), lit(0)).otherwise(col("R6_Running6")).alias("R6_Running6"), 
        when(col("R7_Running6").isNull(), lit(0)).otherwise(col("R7_Running6")).alias("R7_Running6"), 
        when(col("R8_Running6").isNull(), lit(0)).otherwise(col("R8_Running6")).alias("R8_Running6"), 
        when(col("R9_Running6").isNull(), lit(0)).otherwise(col("R9_Running6")).alias("R9_Running6"), 
        when(col("S0_Running6").isNull(), lit(0)).otherwise(col("S0_Running6")).alias("S0_Running6"), 
        when(col("S1_Running6").isNull(), lit(0)).otherwise(col("S1_Running6")).alias("S1_Running6"), 
        when(col("S2_Running6").isNull(), lit(0)).otherwise(col("S2_Running6")).alias("S2_Running6"), 
        when(col("S3_Running6").isNull(), lit(0)).otherwise(col("S3_Running6")).alias("S3_Running6"), 
        when(col("S4_Running6").isNull(), lit(0)).otherwise(col("S4_Running6")).alias("S4_Running6"), 
        when(col("S5_Running6").isNull(), lit(0)).otherwise(col("S5_Running6")).alias("S5_Running6"), 
        when(col("S6_Running6").isNull(), lit(0)).otherwise(col("S6_Running6")).alias("S6_Running6"), 
        when(col("S7_Running6").isNull(), lit(0)).otherwise(col("S7_Running6")).alias("S7_Running6"), 
        when(col("S8_Running6").isNull(), lit(0)).otherwise(col("S8_Running6")).alias("S8_Running6"), 
        when(col("S9_Running6").isNull(), lit(0)).otherwise(col("S9_Running6")).alias("S9_Running6"), 
        when(col("T0_Running6").isNull(), lit(0)).otherwise(col("T0_Running6")).alias("T0_Running6"), 
        when(col("T1_Running6").isNull(), lit(0)).otherwise(col("T1_Running6")).alias("T1_Running6"), 
        when(col("T2_Running6").isNull(), lit(0)).otherwise(col("T2_Running6")).alias("T2_Running6"), 
        when(col("T3_Running6").isNull(), lit(0)).otherwise(col("T3_Running6")).alias("T3_Running6"), 
        when(col("T4_Running6").isNull(), lit(0)).otherwise(col("T4_Running6")).alias("T4_Running6"), 
        when(col("T5_Running6").isNull(), lit(0)).otherwise(col("T5_Running6")).alias("T5_Running6"), 
        when(col("T6_Running6").isNull(), lit(0)).otherwise(col("T6_Running6")).alias("T6_Running6"), 
        when(col("T7_Running6").isNull(), lit(0)).otherwise(col("T7_Running6")).alias("T7_Running6"), 
        when(col("T8_Running6").isNull(), lit(0)).otherwise(col("T8_Running6")).alias("T8_Running6"), 
        when(col("U0_Running6").isNull(), lit(0)).otherwise(col("U0_Running6")).alias("U0_Running6"), 
        when(col("V0_Running6").isNull(), lit(0)).otherwise(col("V0_Running6")).alias("V0_Running6"), 
        when(col("V1_Running6").isNull(), lit(0)).otherwise(col("V1_Running6")).alias("V1_Running6"), 
        when(col("V2_Running6").isNull(), lit(0)).otherwise(col("V2_Running6")).alias("V2_Running6"), 
        when(col("V3_Running6").isNull(), lit(0)).otherwise(col("V3_Running6")).alias("V3_Running6"), 
        when(col("V4_Running6").isNull(), lit(0)).otherwise(col("V4_Running6")).alias("V4_Running6"), 
        when(col("V5_Running6").isNull(), lit(0)).otherwise(col("V5_Running6")).alias("V5_Running6"), 
        when(col("V6_Running6").isNull(), lit(0)).otherwise(col("V6_Running6")).alias("V6_Running6"), 
        when(col("V7_Running6").isNull(), lit(0)).otherwise(col("V7_Running6")).alias("V7_Running6"), 
        when(col("V8_Running6").isNull(), lit(0)).otherwise(col("V8_Running6")).alias("V8_Running6"), 
        when(col("V9_Running6").isNull(), lit(0)).otherwise(col("V9_Running6")).alias("V9_Running6"), 
        when(col("W0_Running6").isNull(), lit(0)).otherwise(col("W0_Running6")).alias("W0_Running6"), 
        when(col("W1_Running6").isNull(), lit(0)).otherwise(col("W1_Running6")).alias("W1_Running6"), 
        when(col("W2_Running6").isNull(), lit(0)).otherwise(col("W2_Running6")).alias("W2_Running6"), 
        when(col("W3_Running6").isNull(), lit(0)).otherwise(col("W3_Running6")).alias("W3_Running6"), 
        when(col("W4_Running6").isNull(), lit(0)).otherwise(col("W4_Running6")).alias("W4_Running6"), 
        when(col("W5_Running6").isNull(), lit(0)).otherwise(col("W5_Running6")).alias("W5_Running6"), 
        when(col("W6_Running6").isNull(), lit(0)).otherwise(col("W6_Running6")).alias("W6_Running6"), 
        when(col("W7_Running6").isNull(), lit(0)).otherwise(col("W7_Running6")).alias("W7_Running6"), 
        when(col("W8_Running6").isNull(), lit(0)).otherwise(col("W8_Running6")).alias("W8_Running6"), 
        when(col("W9_Running6").isNull(), lit(0)).otherwise(col("W9_Running6")).alias("W9_Running6"), 
        when(col("X0_Running6").isNull(), lit(0)).otherwise(col("X0_Running6")).alias("X0_Running6"), 
        when(col("X1_Running6").isNull(), lit(0)).otherwise(col("X1_Running6")).alias("X1_Running6"), 
        when(col("X3_Running6").isNull(), lit(0)).otherwise(col("X3_Running6")).alias("X3_Running6"), 
        when(col("X5_Running6").isNull(), lit(0)).otherwise(col("X5_Running6")).alias("X5_Running6"), 
        when(col("X7_Running6").isNull(), lit(0)).otherwise(col("X7_Running6")).alias("X7_Running6"), 
        when(col("X8_Running6").isNull(), lit(0)).otherwise(col("X8_Running6")).alias("X8_Running6"), 
        when(col("X9_Running6").isNull(), lit(0)).otherwise(col("X9_Running6")).alias("X9_Running6"), 
        when(col("Y0_Running6").isNull(), lit(0)).otherwise(col("Y0_Running6")).alias("Y0_Running6"), 
        when(col("Y2_Running6").isNull(), lit(0)).otherwise(col("Y2_Running6")).alias("Y2_Running6"), 
        when(col("Y3_Running6").isNull(), lit(0)).otherwise(col("Y3_Running6")).alias("Y3_Running6"), 
        when(col("Y6_Running6").isNull(), lit(0)).otherwise(col("Y6_Running6")).alias("Y6_Running6"), 
        when(col("Y7_Running6").isNull(), lit(0)).otherwise(col("Y7_Running6")).alias("Y7_Running6"), 
        when(col("Y8_Running6").isNull(), lit(0)).otherwise(col("Y8_Running6")).alias("Y8_Running6"), 
        when(col("Y9_Running6").isNull(), lit(0)).otherwise(col("Y9_Running6")).alias("Y9_Running6"), 
        when(col("Z0_Running6").isNull(), lit(0)).otherwise(col("Z0_Running6")).alias("Z0_Running6"), 
        when(col("Z1_Running6").isNull(), lit(0)).otherwise(col("Z1_Running6")).alias("Z1_Running6"), 
        when(col("Z2_Running6").isNull(), lit(0)).otherwise(col("Z2_Running6")).alias("Z2_Running6"), 
        when(col("Z3_Running6").isNull(), lit(0)).otherwise(col("Z3_Running6")).alias("Z3_Running6"), 
        when(col("Z4_Running6").isNull(), lit(0)).otherwise(col("Z4_Running6")).alias("Z4_Running6"), 
        when(col("Z5_Running6").isNull(), lit(0)).otherwise(col("Z5_Running6")).alias("Z5_Running6"), 
        when(col("Z6_Running6").isNull(), lit(0)).otherwise(col("Z6_Running6")).alias("Z6_Running6"), 
        when(col("Z7_Running6").isNull(), lit(0)).otherwise(col("Z7_Running6")).alias("Z7_Running6"), 
        when(col("Z8_Running6").isNull(), lit(0)).otherwise(col("Z8_Running6")).alias("Z8_Running6"), 
        when(col("Z9_Running6").isNull(), lit(0)).otherwise(col("Z9_Running6")).alias("Z9_Running6"), 
        when(col("OfLast6_Main_Rx_Costs").isNull(), lit(0))\
          .otherwise(col("OfLast6_Main_Rx_Costs"))\
          .alias("OfLast6_Main_Rx_Costs"), 
        when(col("OfLast6_Main_Diag_Cost").isNull(), lit(0))\
          .otherwise(col("OfLast6_Main_Diag_Cost"))\
          .alias("OfLast6_Main_Diag_Cost"), 
        when(col("ER_Visits_and_Observation_CareRunning3").isNull(), lit(0))\
          .otherwise(col("ER_Visits_and_Observation_CareRunning3"))\
          .alias("ER_Visits_and_Observation_CareRunning3"), 
        when(col("Allergy_ImmunotherapyRunning3").isNull(), lit(0))\
          .otherwise(col("Allergy_ImmunotherapyRunning3"))\
          .alias("Allergy_ImmunotherapyRunning3"), 
        when(col("Allergy_TestingRunning3").isNull(), lit(0))\
          .otherwise(col("Allergy_TestingRunning3"))\
          .alias("Allergy_TestingRunning3"), 
        when(col("AnesthesiaRunning3").isNull(), lit(0))\
          .otherwise(col("AnesthesiaRunning3"))\
          .alias("AnesthesiaRunning3"), 
        when(col("Cardiovascular___Cardiac_Catheterization___Injection_ProceduresRunning3").isNull(), lit(0))\
          .otherwise(col("Cardiovascular___Cardiac_Catheterization___Injection_ProceduresRunning3"))\
          .alias("Cardiovascular___Cardiac_Catheterization___Injection_ProceduresRunning3"), 
        when(col("Cardiovascular___DiagnosticRunning3").isNull(), lit(0))\
          .otherwise(col("Cardiovascular___DiagnosticRunning3"))\
          .alias("Cardiovascular___DiagnosticRunning3"), 
        when(col("Cardiovascular___Noninvasive_Physiologic_Studies_and_ProceduresRunning3").isNull(), lit(0))\
          .otherwise(col("Cardiovascular___Noninvasive_Physiologic_Studies_and_ProceduresRunning3"))\
          .alias("Cardiovascular___Noninvasive_Physiologic_Studies_and_ProceduresRunning3"), 
        when(col("Cardiovascular___Other_ProceduresRunning3").isNull(), lit(0))\
          .otherwise(col("Cardiovascular___Other_ProceduresRunning3"))\
          .alias("Cardiovascular___Other_ProceduresRunning3"), 
        when(col("Chiropractor___Chiropractic_Manipulative_TreatmentRunning3").isNull(), lit(0))\
          .otherwise(col("Chiropractor___Chiropractic_Manipulative_TreatmentRunning3"))\
          .alias("Chiropractor___Chiropractic_Manipulative_TreatmentRunning3"), 
        when(col("ConsultsRunning3").isNull(), lit(0)).otherwise(col("ConsultsRunning3")).alias("ConsultsRunning3"), 
        when(col("DMERunning3").isNull(), lit(0)).otherwise(col("DMERunning3")).alias("DMERunning3"), 
        when(col("Glasses_ContactsRunning3").isNull(), lit(0))\
          .otherwise(col("Glasses_ContactsRunning3"))\
          .alias("Glasses_ContactsRunning3"), 
        when(col("Hearing_Speech_ExamsRunning3").isNull(), lit(0))\
          .otherwise(col("Hearing_Speech_ExamsRunning3"))\
          .alias("Hearing_Speech_ExamsRunning3"), 
        when(col("ImmunizationsRunning3").isNull(), lit(0))\
          .otherwise(col("ImmunizationsRunning3"))\
          .alias("ImmunizationsRunning3"), 
        when(col("IP_Visits___Critical_Care_ServicesRunning3").isNull(), lit(0))\
          .otherwise(col("IP_Visits___Critical_Care_ServicesRunning3"))\
          .alias("IP_Visits___Critical_Care_ServicesRunning3"), 
        when(col("IP_Visits___Hospital_VisitsRunning3").isNull(), lit(0))\
          .otherwise(col("IP_Visits___Hospital_VisitsRunning3"))\
          .alias("IP_Visits___Hospital_VisitsRunning3"), 
        when(col("IP_Visits___Neonatal_VisitsRunning3").isNull(), lit(0))\
          .otherwise(col("IP_Visits___Neonatal_VisitsRunning3"))\
          .alias("IP_Visits___Neonatal_VisitsRunning3"), 
        when(col("IP_Visits___Newborn_CareRunning3").isNull(), lit(0))\
          .otherwise(col("IP_Visits___Newborn_CareRunning3"))\
          .alias("IP_Visits___Newborn_CareRunning3"), 
        when(col("IP_Visits___Nursing_Facility_ServicesRunning3").isNull(), lit(0))\
          .otherwise(col("IP_Visits___Nursing_Facility_ServicesRunning3"))\
          .alias("IP_Visits___Nursing_Facility_ServicesRunning3"), 
        when(col("Maternity_DeliveriesRunning3").isNull(), lit(0))\
          .otherwise(col("Maternity_DeliveriesRunning3"))\
          .alias("Maternity_DeliveriesRunning3"), 
        when(col("Maternity_OtherRunning3").isNull(), lit(0))\
          .otherwise(col("Maternity_OtherRunning3"))\
          .alias("Maternity_OtherRunning3"), 
        when(col("Medical___Diagnostic___BiofeedbackRunning3").isNull(), lit(0))\
          .otherwise(col("Medical___Diagnostic___BiofeedbackRunning3"))\
          .alias("Medical___Diagnostic___BiofeedbackRunning3"), 
        when(col("Medical___Diagnostic___Central_Nervous_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Medical___Diagnostic___Central_Nervous_SystemRunning3"))\
          .alias("Medical___Diagnostic___Central_Nervous_SystemRunning3"), 
        when(col("Medical___Diagnostic___ENTRunning3").isNull(), lit(0))\
          .otherwise(col("Medical___Diagnostic___ENTRunning3"))\
          .alias("Medical___Diagnostic___ENTRunning3"), 
        when(col("Medical___Diagnostic___GastroenterologyRunning3").isNull(), lit(0))\
          .otherwise(col("Medical___Diagnostic___GastroenterologyRunning3"))\
          .alias("Medical___Diagnostic___GastroenterologyRunning3"), 
        when(col("Medical___Diagnostic___Neurology_and_Neuromuscular_ProceduresRunning3").isNull(), lit(0))\
          .otherwise(col("Medical___Diagnostic___Neurology_and_Neuromuscular_ProceduresRunning3"))\
          .alias("Medical___Diagnostic___Neurology_and_Neuromuscular_ProceduresRunning3"), 
        when(col("Medical___Diagnostic___VascularRunning3").isNull(), lit(0))\
          .otherwise(col("Medical___Diagnostic___VascularRunning3"))\
          .alias("Medical___Diagnostic___VascularRunning3"), 
        when(col("Miscellaneous_MedicalRunning3").isNull(), lit(0))\
          .otherwise(col("Miscellaneous_MedicalRunning3"))\
          .alias("Miscellaneous_MedicalRunning3"), 
        when(col("Non_Prescription_DrugsRunning3").isNull(), lit(0))\
          .otherwise(col("Non_Prescription_DrugsRunning3"))\
          .alias("Non_Prescription_DrugsRunning3"), 
        when(col("Non_Standard_BenefitRunning3").isNull(), lit(0))\
          .otherwise(col("Non_Standard_BenefitRunning3"))\
          .alias("Non_Standard_BenefitRunning3"), 
        when(col("Office_Home_Visits___Care_Plan_Oversight_ServicesRunning3").isNull(), lit(0))\
          .otherwise(col("Office_Home_Visits___Care_Plan_Oversight_ServicesRunning3"))\
          .alias("Office_Home_Visits___Care_Plan_Oversight_ServicesRunning3"), 
        when(col("Office_Home_Visits___Office_VisitsRunning3").isNull(), lit(0))\
          .otherwise(col("Office_Home_Visits___Office_VisitsRunning3"))\
          .alias("Office_Home_Visits___Office_VisitsRunning3"), 
        when(col("Office_Home_Visits___Prolonged_ServicesRunning3").isNull(), lit(0))\
          .otherwise(col("Office_Home_Visits___Prolonged_ServicesRunning3"))\
          .alias("Office_Home_Visits___Prolonged_ServicesRunning3"), 
        when(col("Office_Home_Visits___Rest_HomeRunning3").isNull(), lit(0))\
          .otherwise(col("Office_Home_Visits___Rest_HomeRunning3"))\
          .alias("Office_Home_Visits___Rest_HomeRunning3"), 
        when(col("Office_Home_Visits___Telephonic_and_EmailRunning3").isNull(), lit(0))\
          .otherwise(col("Office_Home_Visits___Telephonic_and_EmailRunning3"))\
          .alias("Office_Home_Visits___Telephonic_and_EmailRunning3"), 
        when(col("Pathology_and_LabRunning3").isNull(), lit(0))\
          .otherwise(col("Pathology_and_LabRunning3"))\
          .alias("Pathology_and_LabRunning3"), 
        when(col("PDN_HHRunning3").isNull(), lit(0)).otherwise(col("PDN_HHRunning3")).alias("PDN_HHRunning3"), 
        when(col("Physical_ExamsRunning3").isNull(), lit(0))\
          .otherwise(col("Physical_ExamsRunning3"))\
          .alias("Physical_ExamsRunning3"), 
        when(col("Physical_TherapyRunning3").isNull(), lit(0))\
          .otherwise(col("Physical_TherapyRunning3"))\
          .alias("Physical_TherapyRunning3"), 
        when(col("Psychiatric_Alcohol_Drug_AbuseRunning3").isNull(), lit(0))\
          .otherwise(col("Psychiatric_Alcohol_Drug_AbuseRunning3"))\
          .alias("Psychiatric_Alcohol_Drug_AbuseRunning3"), 
        when(col("Radiology___CT_MRI_PETRunning3").isNull(), lit(0))\
          .otherwise(col("Radiology___CT_MRI_PETRunning3"))\
          .alias("Radiology___CT_MRI_PETRunning3"), 
        when(col("Radiology___Diagnostic___Bone_Joint_StudiesRunning3").isNull(), lit(0))\
          .otherwise(col("Radiology___Diagnostic___Bone_Joint_StudiesRunning3"))\
          .alias("Radiology___Diagnostic___Bone_Joint_StudiesRunning3"), 
        when(col("Radiology___Diagnostic___Diagnostic_ImagingRunning3").isNull(), lit(0))\
          .otherwise(col("Radiology___Diagnostic___Diagnostic_ImagingRunning3"))\
          .alias("Radiology___Diagnostic___Diagnostic_ImagingRunning3"), 
        when(col("Radiology___Diagnostic___Other_ProceduresRunning3").isNull(), lit(0))\
          .otherwise(col("Radiology___Diagnostic___Other_ProceduresRunning3"))\
          .alias("Radiology___Diagnostic___Other_ProceduresRunning3"), 
        when(col("Radiology___NuclearRunning3").isNull(), lit(0))\
          .otherwise(col("Radiology___NuclearRunning3"))\
          .alias("Radiology___NuclearRunning3"), 
        when(col("Radiology___TherapeuticRunning3").isNull(), lit(0))\
          .otherwise(col("Radiology___TherapeuticRunning3"))\
          .alias("Radiology___TherapeuticRunning3"), 
        when(col("Surgery___Auditory_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Auditory_SystemRunning3"))\
          .alias("Surgery___Auditory_SystemRunning3"), 
        when(col("Surgery___Cardiovascular_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Cardiovascular_SystemRunning3"))\
          .alias("Surgery___Cardiovascular_SystemRunning3"), 
        when(col("Surgery___Digestive_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Digestive_SystemRunning3"))\
          .alias("Surgery___Digestive_SystemRunning3"), 
        when(col("Surgery___Endocrine_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Endocrine_SystemRunning3"))\
          .alias("Surgery___Endocrine_SystemRunning3"), 
        when(col("Surgery___Eye_and_Ocular_AdnexaRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Eye_and_Ocular_AdnexaRunning3"))\
          .alias("Surgery___Eye_and_Ocular_AdnexaRunning3"), 
        when(col("Surgery___Female_Genital_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Female_Genital_SystemRunning3"))\
          .alias("Surgery___Female_Genital_SystemRunning3"), 
        when(col("Surgery___General___Needle_AspirationRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___General___Needle_AspirationRunning3"))\
          .alias("Surgery___General___Needle_AspirationRunning3"), 
        when(col("Surgery___Hemic_and_LymphaticRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Hemic_and_LymphaticRunning3"))\
          .alias("Surgery___Hemic_and_LymphaticRunning3"), 
        when(col("Surgery___Integumentary_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Integumentary_SystemRunning3"))\
          .alias("Surgery___Integumentary_SystemRunning3"), 
        when(col("Surgery___Integumentary_System___Destruction__Benign_or_Premalignant_LesionsRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Integumentary_System___Destruction__Benign_or_Premalignant_LesionsRunning3"))\
          .alias("Surgery___Integumentary_System___Destruction__Benign_or_Premalignant_LesionsRunning3"), 
        when(col("Surgery___Integumentary_System___Destruction__Malignant_LesionsRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Integumentary_System___Destruction__Malignant_LesionsRunning3"))\
          .alias("Surgery___Integumentary_System___Destruction__Malignant_LesionsRunning3"), 
        when(col("Surgery___Integumentary_System___Excision_of_Malignant_LesionsRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Integumentary_System___Excision_of_Malignant_LesionsRunning3"))\
          .alias("Surgery___Integumentary_System___Excision_of_Malignant_LesionsRunning3"), 
        when(col("Surgery___Male_Genital_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Male_Genital_SystemRunning3"))\
          .alias("Surgery___Male_Genital_SystemRunning3"), 
        when(col("Surgery___MusculoskeletalRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___MusculoskeletalRunning3"))\
          .alias("Surgery___MusculoskeletalRunning3"), 
        when(col("Surgery___Nervous_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Nervous_SystemRunning3"))\
          .alias("Surgery___Nervous_SystemRunning3"), 
        when(col("Surgery___Respiratory_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Respiratory_SystemRunning3"))\
          .alias("Surgery___Respiratory_SystemRunning3"), 
        when(col("Surgery___Urinary_SystemRunning3").isNull(), lit(0))\
          .otherwise(col("Surgery___Urinary_SystemRunning3"))\
          .alias("Surgery___Urinary_SystemRunning3"), 
        when(col("Urgent_Care_VisitsRunning3").isNull(), lit(0))\
          .otherwise(col("Urgent_Care_VisitsRunning3"))\
          .alias("Urgent_Care_VisitsRunning3"), 
        when(col("Vision_ExamsRunning3").isNull(), lit(0))\
          .otherwise(col("Vision_ExamsRunning3"))\
          .alias("Vision_ExamsRunning3"), 
        when(col("Well_Baby_ExamsRunning3").isNull(), lit(0))\
          .otherwise(col("Well_Baby_ExamsRunning3"))\
          .alias("Well_Baby_ExamsRunning3"), 
        col("MEMBER_AGE2"), 
        col("IP_Running6"), 
        col("YEARMONTH"), 
        col("MBR_INDV_BE_KEY"), 
        col("Tertiary_Diagnosis_Running3"), 
        col("Secondary_Rx_Running3"), 
        col("MBR_SK"), 
        col("Relative_IP_Month"), 
        col("IP_Running3"), 
        col("OfLast6_Main_Diag"), 
        col("IP_Running3_Max"), 
        col("Tertiary_RxCosts_Running3"), 
        col("First_IP"), 
        col("IP_Running6_Max"), 
        col("IP_PreviousMonth"), 
        col("Tertiary_Rx_Running3"), 
        col("Primary_Rx_Running3"), 
        col("Secondary_DiagnosisCosts_Running3"), 
        col("Concat_ORDER_TST_NM_Running3"), 
        col("MBR_GNDR_CD"), 
        col("Primary_RxCosts_Running3"), 
        col("OfLast6_Main_Rx"), 
        col("TOT_MONTHS"), 
        col("Primary_DiagnosisCosts_Running3"), 
        col("Primary_Diagnosis"), 
        col("RecordID"), 
        col("Member_Age"), 
        col("Primary_Diagnosis_Running3"), 
        col("Secondary_RxCosts_Running3"), 
        col("Secondary_Diagnosis_Running3"), 
        col("IP_Record")
    )
