from pyspark.sql import *
from pyspark.sql.functions import *
from pyspark.sql.types import *
from prophecy.utils import *
from prophecy.libs import typed_lit
from job.config.ConfigStore import *
from job.udfs.UDFs import *

def Summarize_735(spark: SparkSession, in0: DataFrame) -> DataFrame:
    df1 = in0.groupBy(col("MBR_INDV_BE_KEY"), col("YEARMONTH"))

    return df1.agg(
        sum(col("E46")).alias("Sum_E46"), 
        sum(col("E43")).alias("Sum_E43"), 
        sum(col("E10")).alias("Sum_E10"), 
        sum(col("E80")).alias("Sum_E80"), 
        sum(col("E74")).alias("Sum_E74"), 
        sum(col("E89")).alias("Sum_E89"), 
        sum(col("E21")).alias("Sum_E21"), 
        sum(col("E71")).alias("Sum_E71"), 
        sum(col("E23")).alias("Sum_E23"), 
        sum(col("E08")).alias("Sum_E08"), 
        sum(col("E50")).alias("Sum_E50"), 
        sum(col("E35")).alias("Sum_E35"), 
        sum(col("E05")).alias("Sum_E05"), 
        sum(col("E84")).alias("Sum_E84"), 
        sum(col("E27")).alias("Sum_E27"), 
        sum(col("E16")).alias("Sum_E16"), 
        sum(col("E65")).alias("Sum_E65"), 
        sum(col("E77")).alias("Sum_E77"), 
        sum(col("E54")).alias("Sum_E54"), 
        sum(col("E32")).alias("Sum_E32"), 
        sum(col("E61")).alias("Sum_E61"), 
        sum(col("E45")).alias("Sum_E45"), 
        sum(col("E67")).alias("Sum_E67"), 
        sum(col("E11")).alias("Sum_E11"), 
        sum(col("E75")).alias("Sum_E75"), 
        sum(col("E56")).alias("Sum_E56"), 
        sum(col("E51")).alias("Sum_E51"), 
        sum(col("E22")).alias("Sum_E22"), 
        sum(col("E72")).alias("Sum_E72"), 
        sum(col("E83")).alias("Sum_E83"), 
        sum(col("E09")).alias("Sum_E09"), 
        sum(col("E40")).alias("Sum_E40"), 
        sum(col("E26")).alias("Sum_E26"), 
        sum(col("E04")).alias("Sum_E04"), 
        sum(col("E87")).alias("Sum_E87"), 
        sum(col("E01")).alias("Sum_E01"), 
        sum(col("E34")).alias("Sum_E34"), 
        sum(col("E15")).alias("Sum_E15"), 
        sum(col("E25")).alias("Sum_E25"), 
        sum(col("E66")).alias("Sum_E66"), 
        sum(col("E63")).alias("Sum_E63"), 
        sum(col("E44")).alias("Sum_E44"), 
        sum(col("E76")).alias("Sum_E76"), 
        sum(col("E52")).alias("Sum_E52"), 
        sum(col("E55")).alias("Sum_E55"), 
        sum(col("E03")).alias("Sum_E03"), 
        sum(col("E41")).alias("Sum_E41"), 
        sum(col("E30")).alias("Sum_E30"), 
        sum(col("E73")).alias("Sum_E73"), 
        sum(col("E07")).alias("Sum_E07"), 
        sum(col("E29")).alias("Sum_E29"), 
        sum(col("E59")).alias("Sum_E59"), 
        sum(col("E79")).alias("Sum_E79"), 
        sum(col("E86")).alias("Sum_E86"), 
        sum(col("E00")).alias("Sum_E00"), 
        sum(col("E70")).alias("Sum_E70"), 
        sum(col("E58")).alias("Sum_E58"), 
        sum(col("E88")).alias("Sum_E88"), 
        sum(col("E24")).alias("Sum_E24"), 
        sum(col("E13")).alias("Sum_E13"), 
        sum(col("E02")).alias("Sum_E02"), 
        sum(col("E20")).alias("Sum_E20"), 
        sum(col("E06")).alias("Sum_E06"), 
        sum(col("E85")).alias("Sum_E85"), 
        sum(col("E64")).alias("Sum_E64"), 
        sum(col("E78")).alias("Sum_E78"), 
        sum(col("E36")).alias("Sum_E36"), 
        sum(col("E31")).alias("Sum_E31"), 
        sum(col("E42")).alias("Sum_E42"), 
        sum(col("E60")).alias("Sum_E60"), 
        sum(col("E53")).alias("Sum_E53"), 
        sum(col("E28")).alias("Sum_E28")
    )
